// Code generated by codegen/generate.py; DO NOT EDIT.

package llmkit

import "testing"

// TestEveryProviderFactory_Constructs exercises every per-provider
// factory + the generic New escape hatch. Generated from the provider
// A-Boxes so the constructor surface and its test stay in lockstep.
func TestEveryProviderFactory_Constructs(t *testing.T) {
	pairs := []struct {
		label   string
		factory func(string) *Client
	}{
		{"<custom>", func(k string) *Client { return New("custom", k) }},
		{"ai21", Ai21},
		{"anthropic", Anthropic},
		{"assemblyai", Assemblyai},
		{"azure", Azure},
		{"bedrock", Bedrock},
		{"cerebras", Cerebras},
		{"cohere", Cohere},
		{"deepseek", Deepseek},
		{"doubao", Doubao},
		{"ernie", Ernie},
		{"fireworks", Fireworks},
		{"google", Google},
		{"grok", Grok},
		{"groq", Groq},
		{"inworld", Inworld},
		{"jan", Jan},
		{"llamacpp", Llamacpp},
		{"lmstudio", Lmstudio},
		{"minimax", Minimax},
		{"mistral", Mistral},
		{"moonshot", Moonshot},
		{"ollama", Ollama},
		{"openai", Openai},
		{"openrouter", Openrouter},
		{"perplexity", Perplexity},
		{"pixverse", Pixverse},
		{"qwen", Qwen},
		{"recraft", Recraft},
		{"sambanova", Sambanova},
		{"together", Together},
		{"vertex", Vertex},
		{"vidu", Vidu},
		{"vllm", Vllm},
		{"workersai", Workersai},
		{"yi", Yi},
		{"zhipu", Zhipu},
	}
	for _, pair := range pairs {
		c := pair.factory("k")
		if c == nil {
			t.Fatalf("%s: factory returned nil", pair.label)
		}
		if c.provider.apiKey != "k" {
			t.Fatalf("%s: apiKey not stored (got %q)", pair.label, c.provider.apiKey)
		}
	}
}
