// Code generated by codegen/generate.py; DO NOT EDIT.

// Typed-builder API (ADR-009 / plan 016 / plan 018). Hoisted into
// package llmkit at the root once the legacy free-function layer
// was deleted (ADR-010).
package llmkit

// providerConfig holds per-provider auth + endpoint details.
// baseURL is an internal override mainly used by tests pointing
// at httptest.Server URLs; per-provider constructors leave it
// empty so the canonical endpoint from the provider catalog wins.
type providerConfig struct {
	name    string
	apiKey  string
	baseURL string
}

// toProvider lowers the internal config to a Provider for the
// internal request runtime.
func (pc providerConfig) toProvider(model string) Provider {
	return Provider{Name: pc.name, APIKey: pc.apiKey, Model: model, BaseURL: pc.baseURL}
}

// Client is the entry point for the typed-builder API. Each
// sub-namespace field is a *<Capability> builder prototype tied to
// this client; chain methods return new instances, the field stays
// constant.
type Client struct {
	provider  providerConfig
	Text      *Text
	Image     *Image
	Music     *Music
	Agent     *Agent
	Upload    *Upload
	Models    *Models
	Providers *Providers
}

func newClient(name, apiKey string) *Client {
	c := &Client{provider: providerConfig{name: name, apiKey: apiKey}}
	c.Text = &Text{client: c}
	c.Image = &Image{client: c}
	c.Music = &Music{client: c}
	c.Agent = &Agent{client: c}
	c.Upload = &Upload{client: c}
	c.Models = &Models{client: c}
	c.Providers = &Providers{client: c}
	return c
}

// New constructs a Client for the named provider. Per-provider
// helpers below are ergonomic shortcuts.
func New(name, apiKey string) *Client { return newClient(name, apiKey) }

// === Per-provider constructors ===
func Ai21(apiKey string) *Client       { return newClient("ai21", apiKey) }
func Anthropic(apiKey string) *Client  { return newClient("anthropic", apiKey) }
func Azure(apiKey string) *Client      { return newClient("azure", apiKey) }
func Bedrock(apiKey string) *Client    { return newClient("bedrock", apiKey) }
func Cerebras(apiKey string) *Client   { return newClient("cerebras", apiKey) }
func Cohere(apiKey string) *Client     { return newClient("cohere", apiKey) }
func Deepseek(apiKey string) *Client   { return newClient("deepseek", apiKey) }
func Doubao(apiKey string) *Client     { return newClient("doubao", apiKey) }
func Ernie(apiKey string) *Client      { return newClient("ernie", apiKey) }
func Fireworks(apiKey string) *Client  { return newClient("fireworks", apiKey) }
func Google(apiKey string) *Client     { return newClient("google", apiKey) }
func Grok(apiKey string) *Client       { return newClient("grok", apiKey) }
func Groq(apiKey string) *Client       { return newClient("groq", apiKey) }
func Jan(apiKey string) *Client        { return newClient("jan", apiKey) }
func Llamacpp(apiKey string) *Client   { return newClient("llamacpp", apiKey) }
func Lmstudio(apiKey string) *Client   { return newClient("lmstudio", apiKey) }
func Minimax(apiKey string) *Client    { return newClient("minimax", apiKey) }
func Mistral(apiKey string) *Client    { return newClient("mistral", apiKey) }
func Moonshot(apiKey string) *Client   { return newClient("moonshot", apiKey) }
func Ollama(apiKey string) *Client     { return newClient("ollama", apiKey) }
func Openai(apiKey string) *Client     { return newClient("openai", apiKey) }
func Openrouter(apiKey string) *Client { return newClient("openrouter", apiKey) }
func Perplexity(apiKey string) *Client { return newClient("perplexity", apiKey) }
func Qwen(apiKey string) *Client       { return newClient("qwen", apiKey) }
func Sambanova(apiKey string) *Client  { return newClient("sambanova", apiKey) }
func Together(apiKey string) *Client   { return newClient("together", apiKey) }
func Vertex(apiKey string) *Client     { return newClient("vertex", apiKey) }
func Vllm(apiKey string) *Client       { return newClient("vllm", apiKey) }
func Yi(apiKey string) *Client         { return newClient("yi", apiKey) }
func Zhipu(apiKey string) *Client      { return newClient("zhipu", apiKey) }

// === *Text — ChatCompletion builder ===

// Text accumulates configuration for a ChatCompletion
// call. Chain methods return new instances (immutable); skipped
// terminals live in hand-written text.go / image.go.
type Text struct {
	client           *Client
	middleware       []MiddlewareFn
	caching          bool
	files            []File
	frequencyPenalty *float64
	history          []Message
	parts            []Part
	maxTokens        *int
	model            string
	presencePenalty  *float64
	raw              bool
	reasoningEffort  string
	safetySettings   []SafetySetting
	schema           string
	seed             *int64
	stopSequences    []string
	system           string
	temperature      *float64
	thinkingBudget   *int
	topK             *int
	topP             *float64
}

func (b *Text) AddMiddleware(fns ...MiddlewareFn) *Text {
	out := *b
	out.middleware = append(append([]MiddlewareFn{}, b.middleware...), fns...)
	return &out
}
func (b *Text) Caching() *Text { out := *b; out.caching = true; return &out }
func (b *Text) File(id string) *Text {
	out := *b
	out.files = append(append([]File{}, b.files...), File{ID: id})
	return &out
} // ordered
func (b *Text) FrequencyPenalty(v float64) *Text {
	out := *b
	x := v
	out.frequencyPenalty = &x
	return &out
}
func (b *Text) History(msgs ...Message) *Text {
	out := *b
	out.history = append([]Message{}, msgs...)
	return &out
}
func (b *Text) Image(mime string, data []byte) *Text {
	out := *b
	out.parts = append(append([]Part{}, b.parts...), Part{Image: &MediaRef{MimeType: mime, Bytes: data}})
	return &out
}                                       // ordered
func (b *Text) MaxTokens(n int) *Text   { out := *b; v := n; out.maxTokens = &v; return &out }
func (b *Text) Model(name string) *Text { out := *b; out.model = name; return &out }
func (b *Text) PresencePenalty(v float64) *Text {
	out := *b
	x := v
	out.presencePenalty = &x
	return &out
}
func (b *Text) Raw() *Text { out := *b; out.raw = true; return &out }
func (b *Text) ReasoningEffort(level string) *Text {
	out := *b
	out.reasoningEffort = level
	return &out
}
func (b *Text) SafetySettings(s []SafetySetting) *Text {
	out := *b
	out.safetySettings = s
	return &out
}
func (b *Text) Schema(s string) *Text { out := *b; out.schema = s; return &out }
func (b *Text) Seed(n int64) *Text    { out := *b; v := n; out.seed = &v; return &out }
func (b *Text) StopSequences(seqs ...string) *Text {
	out := *b
	out.stopSequences = append([]string{}, seqs...)
	return &out
}
func (b *Text) System(s string) *Text       { out := *b; out.system = s; return &out }
func (b *Text) Temperature(t float64) *Text { out := *b; v := t; out.temperature = &v; return &out }
func (b *Text) Text(s string) *Text {
	out := *b
	out.parts = append(append([]Part{}, b.parts...), Part{Text: s})
	return &out
}                                          // ordered
func (b *Text) ThinkingBudget(n int) *Text { out := *b; v := n; out.thinkingBudget = &v; return &out }
func (b *Text) TopK(n int) *Text           { out := *b; v := n; out.topK = &v; return &out }
func (b *Text) TopP(v float64) *Text       { out := *b; x := v; out.topP = &x; return &out }

// === *Image — ImageGeneration builder ===

// Image accumulates configuration for a ImageGeneration
// call. Chain methods return new instances (immutable); skipped
// terminals live in hand-written text.go / image.go.
type Image struct {
	client         *Client
	middleware     []MiddlewareFn
	aspectRatio    string
	background     string
	count          *int
	parts          []Part
	imageSize      string
	includeText    bool
	mask           *MediaRef
	model          string
	outputFormat   string
	quality        string
	raw            bool
	safetyFilter   string
	safetySettings []SafetySetting
	extraFields    map[string]any
}

func (b *Image) AddMiddleware(fns ...MiddlewareFn) *Image {
	out := *b
	out.middleware = append(append([]MiddlewareFn{}, b.middleware...), fns...)
	return &out
}
func (b *Image) AspectRatio(r string) *Image { out := *b; out.aspectRatio = r; return &out }
func (b *Image) Background(s string) *Image  { out := *b; out.background = s; return &out }
func (b *Image) Count(n int) *Image          { out := *b; v := n; out.count = &v; return &out }
func (b *Image) Image(mime string, data []byte) *Image {
	out := *b
	out.parts = append(append([]Part{}, b.parts...), Part{Image: &MediaRef{MimeType: mime, Bytes: data}})
	return &out
}                                          // ordered
func (b *Image) ImageSize(s string) *Image { out := *b; out.imageSize = s; return &out }
func (b *Image) IncludeText() *Image       { out := *b; out.includeText = true; return &out }
func (b *Image) Mask(mime string, data []byte) *Image {
	out := *b
	out.mask = &MediaRef{MimeType: mime, Bytes: append([]byte(nil), data...)}
	return &out
}
func (b *Image) Model(name string) *Image     { out := *b; out.model = name; return &out }
func (b *Image) OutputFormat(s string) *Image { out := *b; out.outputFormat = s; return &out }
func (b *Image) Quality(s string) *Image      { out := *b; out.quality = s; return &out }
func (b *Image) Raw() *Image                  { out := *b; out.raw = true; return &out }
func (b *Image) SafetyFilter(s string) *Image { out := *b; out.safetyFilter = s; return &out }
func (b *Image) SafetySettings(s []SafetySetting) *Image {
	out := *b
	out.safetySettings = s
	return &out
}
func (b *Image) Text(s string) *Image {
	out := *b
	out.parts = append(append([]Part{}, b.parts...), Part{Text: s})
	return &out
} // ordered

// === *Music — MusicGeneration builder ===

// Music accumulates configuration for a MusicGeneration
// call. Chain methods return new instances (immutable); skipped
// terminals live in hand-written text.go / image.go.
type Music struct {
	client     *Client
	middleware []MiddlewareFn
	parts      []Part
	model      string
	raw        bool
}

func (b *Music) AddMiddleware(fns ...MiddlewareFn) *Music {
	out := *b
	out.middleware = append(append([]MiddlewareFn{}, b.middleware...), fns...)
	return &out
}
func (b *Music) Lyrics(s string) *Music {
	out := *b
	out.parts = append(append([]Part{}, b.parts...), Part{Lyrics: s})
	return &out
}                                         // ordered
func (b *Music) Model(name string) *Music { out := *b; out.model = name; return &out }
func (b *Music) Raw() *Music              { out := *b; out.raw = true; return &out }
func (b *Music) Text(s string) *Music {
	out := *b
	out.parts = append(append([]Part{}, b.parts...), Part{Text: s})
	return &out
} // ordered

// === *Agent — ToolCalling builder ===

// Agent accumulates configuration for a ToolCalling
// call. Chain methods return new instances (immutable); skipped
// terminals live in hand-written text.go / image.go.
type Agent struct {
	client            *Client
	middleware        []MiddlewareFn
	tools             []Tool
	caching           bool
	frequencyPenalty  *float64
	history           []Message
	maxTokens         *int
	maxToolIterations *int
	model             string
	presencePenalty   *float64
	raw               bool
	reasoningEffort   string
	safetySettings    []SafetySetting
	seed              *int64
	stopSequences     []string
	system            string
	temperature       *float64
	thinkingBudget    *int
	topK              *int
	topP              *float64
	state             *agentState
}

func (b *Agent) AddMiddleware(fns ...MiddlewareFn) *Agent {
	out := *b
	out.middleware = append(append([]MiddlewareFn{}, b.middleware...), fns...)
	out.state = nil
	return &out
}
func (b *Agent) AddTool(t Tool) *Agent {
	out := *b
	out.tools = append(append([]Tool{}, b.tools...), t)
	out.state = nil
	return &out
}
func (b *Agent) Caching() *Agent { out := *b; out.caching = true; out.state = nil; return &out }
func (b *Agent) FrequencyPenalty(v float64) *Agent {
	out := *b
	x := v
	out.frequencyPenalty = &x
	out.state = nil
	return &out
}
func (b *Agent) History(msgs ...Message) *Agent {
	out := *b
	out.history = append([]Message{}, msgs...)
	out.state = nil
	return &out
}
func (b *Agent) MaxTokens(n int) *Agent {
	out := *b
	v := n
	out.maxTokens = &v
	out.state = nil
	return &out
}
func (b *Agent) MaxToolIterations(n int) *Agent {
	out := *b
	v := n
	out.maxToolIterations = &v
	out.state = nil
	return &out
}
func (b *Agent) Model(name string) *Agent { out := *b; out.model = name; out.state = nil; return &out }
func (b *Agent) PresencePenalty(v float64) *Agent {
	out := *b
	x := v
	out.presencePenalty = &x
	out.state = nil
	return &out
}
func (b *Agent) Raw() *Agent { out := *b; out.raw = true; out.state = nil; return &out }
func (b *Agent) ReasoningEffort(level string) *Agent {
	out := *b
	out.reasoningEffort = level
	out.state = nil
	return &out
}
func (b *Agent) SafetySettings(s []SafetySetting) *Agent {
	out := *b
	out.safetySettings = s
	out.state = nil
	return &out
}
func (b *Agent) Seed(n int64) *Agent { out := *b; v := n; out.seed = &v; out.state = nil; return &out }
func (b *Agent) StopSequences(seqs ...string) *Agent {
	out := *b
	out.stopSequences = append([]string{}, seqs...)
	out.state = nil
	return &out
}
func (b *Agent) System(s string) *Agent { out := *b; out.system = s; out.state = nil; return &out }
func (b *Agent) Temperature(t float64) *Agent {
	out := *b
	v := t
	out.temperature = &v
	out.state = nil
	return &out
}
func (b *Agent) ThinkingBudget(n int) *Agent {
	out := *b
	v := n
	out.thinkingBudget = &v
	out.state = nil
	return &out
}
func (b *Agent) TopK(n int) *Agent { out := *b; v := n; out.topK = &v; out.state = nil; return &out }
func (b *Agent) TopP(v float64) *Agent {
	out := *b
	x := v
	out.topP = &x
	out.state = nil
	return &out
}

// === *Upload — FileUpload builder ===

// Upload accumulates configuration for a FileUpload
// call. Chain methods return new instances (immutable); skipped
// terminals live in hand-written text.go / image.go.
type Upload struct {
	client     *Client
	middleware []MiddlewareFn
	bytes      []byte
	filename   string
	mimeType   string
	path       string
}

func (b *Upload) AddMiddleware(fns ...MiddlewareFn) *Upload {
	out := *b
	out.middleware = append(append([]MiddlewareFn{}, b.middleware...), fns...)
	return &out
}
func (b *Upload) Bytes(data []byte) *Upload {
	out := *b
	out.bytes = append([]byte(nil), data...)
	return &out
}
func (b *Upload) Filename(name string) *Upload { out := *b; out.filename = name; return &out }
func (b *Upload) MimeType(mime string) *Upload { out := *b; out.mimeType = mime; return &out }
func (b *Upload) Path(p string) *Upload        { out := *b; out.path = p; return &out }
