// Code generated by codegen/generate.py; DO NOT EDIT.

// Catalogue builder structs (ADR-019). Each builder type holds chain
// state; terminal methods delegate to private hand-coded runtime in
// go/models.go and go/providers.go.

package llmkit

import (
	"context"

	"github.com/aktagon/llmkit-go/providers"
)

// Models is the catalogue builder. Chain methods are immutable;
// List/Get walk the compiled-in slice, Live(ctx) fans out HTTP
// across configured providers, Provider(p) scopes to one provider
// and returns *ScopedModels.
type Models struct {
	client    *Client
	capFilter Capability // empty when WithCapability was not set
}

// WithCapability filters the catalogue to models whose
// ontology-derived Capabilities slice contains c. Composes with
// List (compiled-in), Live (live aggregate), and Provider(p).List.
func (b *Models) WithCapability(c Capability) *Models {
	out := *b
	out.capFilter = c
	return &out
}

// Provider scopes the catalogue to a single Provider and returns
// the *ScopedModels sub-builder on which Raw(), List(ctx), and
// Get(ctx, id) are reachable. Compiled-in *Models.Get(id) is sync;
// scoped *ScopedModels.Get(ctx, id) is the HTTP variant.
func (b *Models) Provider(p Provider) *ScopedModels {
	return &ScopedModels{client: b.client, target: p, capFilter: b.capFilter}
}

// List returns the compiled-in catalogue, filtered by
// WithCapability when set. Sync, no IO, no error.
func (b *Models) List() []ModelInfo {
	return filterCompiledModels(b.capFilter)
}

// Get returns a compiled-in model by ID; the bool reports whether
// an entry was found.
func (b *Models) Get(id string) (ModelInfo, bool) {
	return lookupCompiledModel(id)
}

// Live runs an HTTP fan-out across configured providers and
// returns a LiveResult aggregating the union of successful records
// plus a per-provider error map. WithCapability composes post-fetch.
func (b *Models) Live(ctx context.Context) (LiveResult, error) {
	return b.runLive(ctx)
}

// ScopedModels is the single-provider live-catalogue sub-builder.
// Reached via *Models.Provider(p). Raw() opts into populating
// ModelInfo.Raw with the parsed provider-native record per ADR-014.
type ScopedModels struct {
	client    *Client
	target    Provider
	capFilter Capability
	raw       bool
}

// Raw flags the chain to populate ModelInfo.Raw on each record.
func (b *ScopedModels) Raw() *ScopedModels {
	out := *b
	out.raw = true
	return &out
}

// List performs the live HTTP call for this provider, looping
// through pagination per the provider's PaginationStyle.
func (b *ScopedModels) List(ctx context.Context) ([]ModelInfo, error) {
	return b.runList(ctx)
}

// Get fetches a single live model record by ID.
func (b *ScopedModels) Get(ctx context.Context, id string) (ModelInfo, error) {
	return b.runGet(ctx, id)
}

// Providers is the providers-namespace prototype. List() returns the
// providers with both credentials configured and llm:hasModelsEndpoint
// declared, as secret-free ProviderInfo (ADR-040 PSR-005). The static
// roster of every supported provider is providers.List().
type Providers struct {
	client *Client
}

// List returns the providers eligible for *Models.Live(ctx) as secret-free
// ProviderInfo metadata (ADR-040 PSR-005).
func (b *Providers) List() []providers.ProviderInfo {
	return b.runList()
}
