// Code generated by codegen/generate.py; DO NOT EDIT.

package llmkit

// Canonical wire-fixture inputs (ADR-028 / plan 039), single-sourced
// from ontology/wire-fixtures.ttl. Consumed by the request-wire
// conformance drivers; codegen/lint_wire_witness.py derives witness
// coverage from the same facts.
const (
	wireCachingPrompt                           = "hi"
	wireCachingSystem                           = "a long stable system prefix"
	wireImageEditGoogleFlashModel               = "gemini-3.1-flash-image-preview"
	wireImageEditGoogleFlashPrompt              = "Recolor the square to deep blue"
	wireImageEditGoogleFlashImageMime           = "image/png"
	wireImageEditGoogleFlashImageBase64         = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVR4nGM4YWQEAALyAS2saifrAAAAAElFTkSuQmCC"
	wireImageGenGoogleFlashModel                = "gemini-3.1-flash-image-preview"
	wireImageGenGoogleFlashPrompt               = "A lighthouse on a rocky coastline at dusk"
	wireImageGenGoogleFlashAspectRatio          = "16:9"
	wireImageGenGoogleFlashImageSize            = "2K"
	wireImageGenGoogleProModel                  = "gemini-3-pro-image-preview"
	wireImageGenGoogleProPrompt                 = "A watercolor map of the Baltic Sea"
	wireImageGenGoogleProAspectRatio            = "4:3"
	wireImageGenGoogleProImageSize              = "1K"
	wireImageGenOpenaiModel                     = "gpt-image-2"
	wireImageGenOpenaiPrompt                    = "A minimalist line drawing of a sailboat"
	wireImageGenOpenaiBackground                = "opaque"
	wireImageGenOpenaiCount                     = 1
	wireImageGenOpenaiImageSize                 = "1024x1024"
	wireImageGenOpenaiOutputFormat              = "png"
	wireImageGenOpenaiQuality                   = "low"
	wireOptionsAnthropicModel                   = "claude-sonnet-4-6"
	wireOptionsAnthropicPrompt                  = "Explain in one sentence why the sky appears blue at noon, then write END_OF_ANSWER."
	wireOptionsAnthropicMaxTokens               = 2048
	wireOptionsAnthropicStopSequences           = "END_OF_ANSWER"
	wireOptionsAnthropicThinkingBudget          = 1024
	wireOptionsAnthropicAdaptiveModel           = "claude-opus-4-7"
	wireOptionsAnthropicAdaptivePrompt          = "State the boiling point of water at sea level in Celsius, then write END_OF_ANSWER."
	wireOptionsAnthropicAdaptiveMaxTokens       = 2048
	wireOptionsAnthropicAdaptiveReasoningEffort = "medium"
	wireOptionsAnthropicAdaptiveStopSequences   = "END_OF_ANSWER"
	wireOptionsAnthropicPlainModel              = "claude-sonnet-4-6"
	wireOptionsAnthropicPlainPrompt             = "Name the longest river in Finland, then write END_OF_ANSWER."
	wireOptionsAnthropicPlainMaxTokens          = 1024
	wireOptionsAnthropicPlainStopSequences      = "END_OF_ANSWER"
	wireOptionsAnthropicPlainTemperature        = 0.7
	wireOptionsAnthropicPlainTopK               = 40
	wireOptionsGoogleModel                      = "gemini-3.5-flash"
	wireOptionsGooglePrompt                     = "Name the two largest moons of Jupiter, then write END_OF_ANSWER."
	wireOptionsGoogleMaxTokens                  = 1024
	wireOptionsGoogleReasoningEffort            = "low"
	wireOptionsGoogleSeed                       = 7
	wireOptionsGoogleStopSequences              = "END_OF_ANSWER"
	wireOptionsGoogleTemperature                = 0.7
	wireOptionsGoogleTopK                       = 40
	wireOptionsGoogleTopP                       = 0.9
	wireOptionsGoogleSafetyCategory             = "HARM_CATEGORY_DANGEROUS_CONTENT"
	wireOptionsGoogleSafetyThreshold            = "BLOCK_ONLY_HIGH"
	wireOptionsGoogleGemini25Model              = "gemini-2.5-flash"
	wireOptionsGoogleGemini25Prompt             = "How many planets orbit the Sun? Answer with a number."
	wireOptionsGoogleGemini25MaxTokens          = 1024
	wireOptionsGoogleGemini25Temperature        = 0.5
	wireOptionsGoogleGemini25ThinkingBudget     = 512
	wireOptionsOpenaiGpt4oModel                 = "gpt-4o"
	wireOptionsOpenaiGpt4oPrompt                = "List three primary colors, then write END_OF_LIST."
	wireOptionsOpenaiGpt4oFrequencyPenalty      = 0.25
	wireOptionsOpenaiGpt4oMaxTokens             = 256
	wireOptionsOpenaiGpt4oPresencePenalty       = 0.15
	wireOptionsOpenaiGpt4oSeed                  = 42
	wireOptionsOpenaiGpt4oStopSequences         = "END_OF_LIST"
	wireOptionsOpenaiGpt4oTemperature           = 0.7
	wireOptionsOpenaiGpt4oTopP                  = 0.9
	wireOptionsOpenaiGpt5Model                  = "gpt-5"
	wireOptionsOpenaiGpt5Prompt                 = "Summarize the plot of Hamlet in two sentences."
	wireOptionsOpenaiGpt5MaxTokens              = 1024
	wireOptionsOpenaiGpt5ReasoningEffort        = "low"
	wireOptionsOpenaiGpt5Seed                   = 42
	wireOptionsOpenaiOSeriesModel               = "o4-mini"
	wireOptionsOpenaiOSeriesPrompt              = "What is the capital of Finland?"
	wireOptionsOpenaiOSeriesMaxTokens           = 1024
	wireOptionsOpenaiOSeriesReasoningEffort     = "medium"
	wireOptionsOpenaiOSeriesSeed                = 7
	wireStructuredOutputPrompt                  = "What color is a clear daytime sky?"
	wireStructuredOutputSchema                  = "{\"type\":\"object\",\"properties\":{\"color\":{\"type\":\"string\"}},\"additionalProperties\":false}"
	wireStructuredOutputNestedPrompt            = "Name a coastal city in Finland where a harbor pilot might reside. Reply as structured data."
	wireStructuredOutputNestedSchema            = "{\"type\":\"object\",\"properties\":{\"residence\":{\"type\":\"object\",\"properties\":{\"addresses\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"city\":{\"type\":\"string\"}},\"additionalProperties\":false}}},\"additionalProperties\":false}},\"additionalProperties\":false}"
)
