// Code generated by codegen/generate.py; DO NOT EDIT.

package providers

// APIOptionDef describes a functional option.
type APIOptionDef struct {
	GoFunc     string
	SubOptions []APISubOptionDef
}

// APISubOptionDef describes a sub-option within a functional option.
type APISubOptionDef struct {
	GoFunc      string
	GoParamType string
}

// APIEntryPointDef describes a public entry point function.
type APIEntryPointDef struct {
	GoFunc      string
	GoParamType string
	Comment     string
}

// APIResponseFieldDef describes a response field added by a capability.
type APIResponseFieldDef struct {
	GoFieldName string
	GoFieldType string
	SourcePath  string // CachingDef property name for JSON path lookup
}

// APIOptions returns all functional options.
func APIOptions() []APIOptionDef {
	return []APIOptionDef{
		{GoFunc: "WithCaching", SubOptions: []APISubOptionDef{
			{GoFunc: "CacheTTL", GoParamType: "time.Duration"},
		}},
	}
}

// APIEntryPoints returns all entry point functions.
func APIEntryPoints() []APIEntryPointDef {
	return []APIEntryPointDef{
		{GoFunc: "PromptBatch", GoParamType: "[]Request", Comment: "Blocks until all responses ready. Handles async polling internally."},
		{GoFunc: "SubmitBatch", GoParamType: "[]Request", Comment: "Returns BatchHandle immediately. Use WaitBatch to get results."},
	}
}

// CacheResponseFields returns the response fields for caching.
func CacheResponseFields() []APIResponseFieldDef {
	return []APIResponseFieldDef{
		{GoFieldName: "CacheCreation", GoFieldType: "int", SourcePath: "cacheCreationTokensPath"},
		{GoFieldName: "CacheRead", GoFieldType: "int", SourcePath: "cacheReadTokensPath"},
	}
}

// CacheUsagePaths returns the JSON paths for cache creation and read token counts.
func CacheUsagePaths(provider string) (creationPath, readPath string) {
	cc := CachingConfig(provider)
	if cc == nil {
		return "", ""
	}
	return cc.CreationTokensPath, cc.ReadTokensPath
}
