// Code generated by codegen/generate.py; DO NOT EDIT.

package providers

// APIOptionDef describes a functional option.
type APIOptionDef struct {
	GoFunc     string
	SubOptions []APISubOptionDef
}

// APISubOptionDef describes a sub-option within a functional option.
type APISubOptionDef struct {
	GoFunc      string
	GoParamType string
}

// APIEntryPointDef describes a public entry point function.
type APIEntryPointDef struct {
	GoFunc      string
	GoParamType string
	Comment     string
}

// APIResponseFieldDef describes a response field added by a capability.
type APIResponseFieldDef struct {
	GoFieldName string
	GoFieldType string
	SourcePath  string // CachingDef property name for JSON path lookup
}

// APIOptions returns all functional options.
func APIOptions() []APIOptionDef {
	return []APIOptionDef{
		{GoFunc: "WithAddTool", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithAspectRatio", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithBackground", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithBytes", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithCaching", SubOptions: []APISubOptionDef{
			{GoFunc: "CacheTTL", GoParamType: "time.Duration"},
		}},
		{GoFunc: "WithCount", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithFile", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithFilename", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithFrequencyPenalty", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithHistory", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithImage", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithImageSize", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithIncludeText", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithLyrics", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithMask", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithMaxTokens", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithMaxToolIterations", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithMimeType", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithModel", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithOutputFormat", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithOutputURI", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithPath", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithPresencePenalty", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithProtocol", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithProvider", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithQuality", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithRaw", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithReasoningEffort", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithSafetyFilter", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithSafetySettings", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithSchema", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithSeed", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithStopSequences", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithSystem", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithTemperature", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithText", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithThinkingBudget", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithTopK", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithTopP", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithVoice", SubOptions: []APISubOptionDef{}},
		{GoFunc: "WithWithCapability", SubOptions: []APISubOptionDef{}},
	}
}

// APIEntryPoints returns all entry point functions.
func APIEntryPoints() []APIEntryPointDef {
	return []APIEntryPointDef{
		{GoFunc: "Agent", GoParamType: "Provider", Comment: "Constructs a stateful Agent that drives a multi-turn tool-calling loop. Per-language naming: Go NewAgent, TS class Agent, Python class Agent, Rust struct Agent."},
		{GoFunc: "Batch", GoParamType: "[]Request", Comment: "Queues a batch and returns a BatchHandle immediately (ADR-064). A text execution mode on the *Text builder (parallel to Stream); the chain's accumulated config (System, Schema, Model, ...) applies to every prompt in the variadic. Use the handle's Wait to block for results, or Poll to drive the loop from your own orchestrator."},
		{GoFunc: "GenerateImage", GoParamType: "ImageRequest", Comment: "Synchronous text-to-image and image-to-image. Input is ImageRequest{ Model, Prompt, Parts []Part } where Parts is a positionally-ordered sequence of llm:Part (text or image MediaRef). Prompt is a sugar field for the text-only case (XOR with Parts; runtime synthesises []Part{Text(Prompt)} when only Prompt is set). Returns ImageResponse{ Images []ImageData, Text string, Usage }."},
		{GoFunc: "GenerateMusic", GoParamType: "MusicRequest", Comment: "Synchronous text-to-music. Input is MusicRequest{ Model, Prompt, Parts []Part } where Parts is a positionally-ordered sequence of llm:Part (text prompt or Lyrics). Prompt is a sugar field for the prompt-only case (XOR with Parts; runtime synthesises []Part{Text(Prompt)} when only Prompt is set). Returns MusicResponse{ Audio []AudioData, Text string, Usage }."},
		{GoFunc: "GenerateSpeech", GoParamType: "SpeechRequest", Comment: "Synchronous text-to-speech. Input is SpeechRequest{ Model, Voice, Text } — Text is the single utterance to speak (single-turn; no Message/Role wrapper, ADR-049 SPK-003), Voice is the request-data selector (ADR-021) validated pre-flight against the provider's availableVoice catalogue. Returns SpeechResponse{ Audio AudioData, Usage }."},
		{GoFunc: "Poll", GoParamType: "BatchHandle", Comment: "Performs exactly ONE provider round-trip and returns the normalized JobStatus{state, result?, cause?, rawStatus} (ADR-063 POLL-001) — the enterprise seam for callers driving the poll loop from their own orchestrator. Wait is a thin loop over Poll (POLL-003). The shared poll primitive: the same method is on TranscriptionHandle (POLL-007 holds it across all four SDKs)."},
		{GoFunc: "Prompt", GoParamType: "Request", Comment: "One-shot synchronous request. Returns Response with text + Usage tokens."},
		{GoFunc: "PromptStream", GoParamType: "Request", Comment: "Streaming variant. Calls a per-chunk callback as deltas arrive; returns the accumulated Response on stream close."},
		{GoFunc: "Submit", GoParamType: "TranscriptionRequest", Comment: "Asynchronous speech-to-text submit. Input is TranscriptionRequest{ Parts []Part } carrying exactly one audio Part — parts.Audio(url) (a public URL submitted directly as audio_url) or parts.AudioBytes(mime, raw) (local bytes the runtime uploads first to obtain an upload_url, STT-005). A request without exactly one audio part is rejected pre-flight (STT-003). Returns a TranscriptionHandle immediately; poll it with Wait."},
		{GoFunc: "Submit", GoParamType: "VideoRequest", Comment: "Asynchronous text/image-to-video submit. Input is VideoRequest{ Model, Prompt, Parts []Part } where Parts is a positionally-ordered sequence of llm:Part (text prompt or image-to-video reference). Prompt is a sugar field for the prompt-only case (XOR with Parts; runtime synthesises []Part{Text(Prompt)} when only Prompt is set). Returns a VideoHandle immediately; poll it with Wait."},
		{GoFunc: "Supports", GoParamType: "Capability", Comment: "Client.Supports(Capability) — true iff an explicit request for the capability will not hard-fail pre-flight on this client's provider (ADR-030). Gated arms (caching, batching, file_upload, image_generation) dispatch the same generated *_config(provider) lookup as the strict validation paths, so the query and the error cannot drift; capabilities with no provider-level pre-flight gate return true. Says nothing about per-model or per-option rejections — use the catalogue's ModelInfo.Capabilities for model-level facts. Sync, no IO, infallible."},
		{GoFunc: "Transcribe", GoParamType: "TranscriptionRequest", Comment: "Synchronous speech-to-text (ADR-051): one multipart/form-data POST returns the finished TranscriptionResponse directly — no job handle. Input is TranscriptionRequest{ Model, Parts } carrying exactly one inline-bytes audio Part (parts.AudioBytes(mime, raw)); a remote URL is rejected pre-flight (OpenAI ingests no URL — the inverse of AssemblyAI). Available only on sync providers (llm:transcriptionInteraction sync); calling it on an async provider, or Submit/Wait on a sync provider, is a pre-flight ValidationError naming the supported terminal."},
		{GoFunc: "UploadFile", GoParamType: "Bytes", Comment: "Uploads a file and returns a File handle suitable for inclusion in a Request.files slice."},
		{GoFunc: "Wait", GoParamType: "BatchHandle", Comment: "Polls the provider until the batch handle reaches terminal state, then returns the ordered list of Responses. Hand-written on BatchHandle (mirrors VideoHandle.Wait / TranscriptionHandle.Wait), not a builder terminal."},
		{GoFunc: "Wait", GoParamType: "TranscriptionHandle", Comment: "Polls the provider (per the handle's poll endpoint + status mapping) until the job reaches status=completed, then returns a TranscriptionResponse carrying the transcript text and timing segments. A status=error job surfaces as an error (never a silent empty success). Hand-written on TranscriptionHandle (not a *Transcription builder terminal), mirroring VideoHandle.Wait / BatchHandle.Wait."},
		{GoFunc: "Wait", GoParamType: "VideoHandle", Comment: "Polls the provider (per the handle's submit endpoint + wire shape) until the job reaches a terminal state (status=done), then returns a VideoResponse. Poll cadence + timeout use per-provider defaults, overridable via chain option (ADR-034 D2). A failed/expired job surfaces as an error. Hand-written on VideoHandle (not a *Video builder terminal), mirroring BatchHandle.Wait."},
	}
}

// CacheResponseFields returns the response fields for caching.
func CacheResponseFields() []APIResponseFieldDef {
	return []APIResponseFieldDef{
		{GoFieldName: "Audio", GoFieldType: "[]AudioData", SourcePath: "audioPath"},
		{GoFieldName: "Audio", GoFieldType: "AudioData", SourcePath: "audioPath"},
		{GoFieldName: "CacheRead", GoFieldType: "int", SourcePath: "cacheReadTokensPath"},
		{GoFieldName: "CacheWrite", GoFieldType: "int", SourcePath: "cacheWriteTokensPath"},
		{GoFieldName: "FinishMessage", GoFieldType: "string", SourcePath: "finishMessagePath"},
		{GoFieldName: "FinishReason", GoFieldType: "string", SourcePath: "finishReasonPath"},
		{GoFieldName: "Images", GoFieldType: "[]ImageData", SourcePath: "candidates[0].content.parts[*].inlineData"},
		{GoFieldName: "Input", GoFieldType: "int", SourcePath: "usageInputPath"},
		{GoFieldName: "Output", GoFieldType: "int", SourcePath: "usageOutputPath"},
		{GoFieldName: "Reasoning", GoFieldType: "int", SourcePath: "reasoningTokensPath"},
		{GoFieldName: "Text", GoFieldType: "string", SourcePath: "candidates[0].content.parts[*].text"},
		{GoFieldName: "Videos", GoFieldType: "[]VideoData", SourcePath: "video"},
	}
}

// CacheUsagePaths returns the JSON paths for cache write and read token counts.
func CacheUsagePaths(provider string) (writePath, readPath string) {
	cc := CachingConfig(provider)
	if cc == nil {
		return "", ""
	}
	return cc.WriteTokensPath, cc.ReadTokensPath
}
