// Code generated by codegen/generate.py; DO NOT EDIT.

package providers

// Batch input mode discriminators.
const (
	BatchInlineRequests     = "InlineRequests"
	BatchFileReferenceInput = "FileReferenceInput"
)

// BatchDef holds provider-specific batch processing configuration.
type BatchDef struct {
	InputMode        string // BatchInlineRequests or BatchFileReferenceInput
	InputField       string // request field for file reference (OpenAI)
	FilePurpose      string // file upload purpose value
	RequestWrapper   string // field name wrapping individual requests
	CompletionWindow string // time window for batch completion (e.g., "24h")
	EndpointPath     string // API endpoint path for JSONL batch requests
	ItemBodyField    string // field nesting request body in each item (e.g., "params" for Anthropic)
	ResultBodyPath   string // JSON path from each JSONL result line to the response body
	Lifecycle        *ResourceLifecycleDef
}

// BatchConfig returns the batch config for a provider.
func BatchConfig(provider string) *BatchDef {
	switch provider {
	case Anthropic:
		return &BatchDef{
			InputMode:        "InlineRequests",
			InputField:       "",
			FilePurpose:      "",
			RequestWrapper:   "requests",
			CompletionWindow: "",
			EndpointPath:     "",
			ItemBodyField:    "params",
			ResultBodyPath:   "result.message",
			Lifecycle: &ResourceLifecycleDef{
				CreateEndpoint:      "/v1/messages/batches",
				ResponseIdPath:      "id",
				ReferenceField:      "",
				PollingEndpoint:     "",
				PollingStatusPath:   "processing_status",
				PollingDoneValue:    "ended",
				ResultEndpoint:      "/v1/messages/batches/{id}/results",
				ResultResponsePath:  "",
				ResultFileIdPath:    "",
				FileContentEndpoint: "",
			},
		}
	case Google:
		return &BatchDef{
			InputMode:        "InlineRequests",
			InputField:       "",
			FilePurpose:      "",
			RequestWrapper:   "requests",
			CompletionWindow: "",
			EndpointPath:     "",
			ItemBodyField:    "",
			ResultBodyPath:   "",
		}
	case OpenAI:
		return &BatchDef{
			InputMode:        "FileReferenceInput",
			InputField:       "input_file_id",
			FilePurpose:      "batch",
			RequestWrapper:   "",
			CompletionWindow: "24h",
			EndpointPath:     "/v1/chat/completions",
			ItemBodyField:    "",
			ResultBodyPath:   "response.body",
			Lifecycle: &ResourceLifecycleDef{
				CreateEndpoint:      "/v1/batches",
				ResponseIdPath:      "id",
				ReferenceField:      "",
				PollingEndpoint:     "",
				PollingStatusPath:   "status",
				PollingDoneValue:    "completed",
				ResultEndpoint:      "",
				ResultResponsePath:  "",
				ResultFileIdPath:    "output_file_id",
				FileContentEndpoint: "/v1/files/{id}/content",
			},
		}
	default:
		return nil
	}
}
