// Code generated by codegen/generate.py; DO NOT EDIT.

package providers

// Caching mode discriminators.
const (
	CachingAutomatic = "AutomaticCaching"
	CachingExplicit  = "ExplicitCaching"
	CachingResource  = "ResourceCaching"
)

// ResourceLifecycleDef holds create/poll/reference lifecycle configuration.
type ResourceLifecycleDef struct {
	CreateEndpoint      string
	ResponseIdPath      string
	ReferenceField      string
	PollingEndpoint     string
	PollingStatusPath   string
	PollingDoneValue    string
	ResultEndpoint      string
	ResultResponsePath  string
	ResultFileIdPath    string // JSON path to output file ID in poll response (OpenAI batch)
	FileContentEndpoint string // URL path template for downloading file content
}

// CachingDef holds provider-specific prompt caching configuration.
type CachingDef struct {
	Mode               string // CachingAutomatic, CachingExplicit, or CachingResource
	ControlType        string // cache_control type (e.g., "ephemeral")
	CreationTokensPath string // JSON path to cache creation tokens in response
	ReadTokensPath     string // JSON path to cache read tokens in response
	DefaultTTL         string // default TTL in seconds
	Lifecycle          *ResourceLifecycleDef
}

// CachingConfig returns the caching config for a provider.
func CachingConfig(provider string) *CachingDef {
	switch provider {
	case Anthropic:
		return &CachingDef{
			Mode:               "ExplicitCaching",
			ControlType:        "ephemeral",
			CreationTokensPath: "usage.cache_creation_input_tokens",
			ReadTokensPath:     "usage.cache_read_input_tokens",
			DefaultTTL:         "300",
		}
	case Google:
		return &CachingDef{
			Mode:               "ResourceCaching",
			ControlType:        "",
			CreationTokensPath: "",
			ReadTokensPath:     "usageMetadata.cachedContentTokenCount",
			DefaultTTL:         "3600",
			Lifecycle: &ResourceLifecycleDef{
				CreateEndpoint:      "/v1beta/cachedContents",
				ResponseIdPath:      "name",
				ReferenceField:      "cachedContent",
				PollingEndpoint:     "",
				PollingStatusPath:   "",
				PollingDoneValue:    "",
				ResultEndpoint:      "",
				ResultResponsePath:  "",
				ResultFileIdPath:    "",
				FileContentEndpoint: "",
			},
		}
	case OpenAI:
		return &CachingDef{
			Mode:               "AutomaticCaching",
			ControlType:        "",
			CreationTokensPath: "",
			ReadTokensPath:     "usage.prompt_tokens_details.cached_tokens",
			DefaultTTL:         "",
		}
	default:
		return nil
	}
}
