// Code generated by codegen/generate.py; DO NOT EDIT.

//go:build integration

package providers_test

import (
	"context"
	"os"
	"testing"

	"github.com/aktagon/llmkit-go"
	"github.com/aktagon/llmkit-go/providers"
)

func TestIntegrationImageGoogleGemini3ProImagePreview(t *testing.T) {
	key := os.Getenv("GOOGLE_API_KEY")
	if key == "" {
		t.Skip("GOOGLE_API_KEY not set")
	}
	if os.Getenv("LLMKIT_RUN_SLOW_IMAGE") == "" {
		t.Skip("LLMKIT_RUN_SLOW_IMAGE not set; skipping gemini-3-pro-image-preview smoke")
	}
	c := llmkit.New(providers.Google, key)
	resp, err := c.Image.Model("gemini-3-pro-image-preview").AspectRatio("1:1").ImageSize("1K").Generate(context.Background(), "A simple red circle on a white background.")
	if err != nil {
		t.Fatal(err)
	}
	if len(resp.Images) == 0 {
		t.Fatal("no images returned")
	}
	if len(resp.Images[0].Bytes) == 0 {
		t.Error("first image has zero bytes")
	}
	if resp.Tokens.Output == 0 {
		t.Error("no output tokens reported (image-output tokens should land in candidatesTokenCount)")
	}
}

func TestIntegrationImageGoogleGemini31FlashImagePreview(t *testing.T) {
	key := os.Getenv("GOOGLE_API_KEY")
	if key == "" {
		t.Skip("GOOGLE_API_KEY not set")
	}
	c := llmkit.New(providers.Google, key)
	resp, err := c.Image.Model("gemini-3.1-flash-image-preview").AspectRatio("1:1").ImageSize("1K").Generate(context.Background(), "A simple red circle on a white background.")
	if err != nil {
		t.Fatal(err)
	}
	if len(resp.Images) == 0 {
		t.Fatal("no images returned")
	}
	if len(resp.Images[0].Bytes) == 0 {
		t.Error("first image has zero bytes")
	}
	if resp.Tokens.Output == 0 {
		t.Error("no output tokens reported (image-output tokens should land in candidatesTokenCount)")
	}
}

func TestIntegrationImageGrokGrokImagineImageQuality(t *testing.T) {
	key := os.Getenv("XAI_API_KEY")
	if key == "" {
		t.Skip("XAI_API_KEY not set")
	}
	c := llmkit.New(providers.Grok, key)
	resp, err := c.Image.Model("grok-imagine-image-quality").AspectRatio("1:1").Generate(context.Background(), "A simple red circle on a white background.")
	if err != nil {
		t.Fatal(err)
	}
	if len(resp.Images) == 0 {
		t.Fatal("no images returned")
	}
	if len(resp.Images[0].Bytes) == 0 {
		t.Error("first image has zero bytes")
	}
}

func TestIntegrationImageOpenAIGptImage1(t *testing.T) {
	key := os.Getenv("OPENAI_API_KEY")
	if key == "" {
		t.Skip("OPENAI_API_KEY not set")
	}
	if os.Getenv("LLMKIT_RUN_SLOW_IMAGE") == "" {
		t.Skip("LLMKIT_RUN_SLOW_IMAGE not set; skipping gpt-image-1 smoke")
	}
	c := llmkit.New(providers.OpenAI, key)
	resp, err := c.Image.Model("gpt-image-1").Generate(context.Background(), "A simple red circle on a white background.")
	if err != nil {
		t.Fatal(err)
	}
	if len(resp.Images) == 0 {
		t.Fatal("no images returned")
	}
	if len(resp.Images[0].Bytes) == 0 {
		t.Error("first image has zero bytes")
	}
	if resp.Tokens.Output == 0 {
		t.Error("no output tokens reported (image-output tokens should land in candidatesTokenCount)")
	}
}

func TestIntegrationImageOpenAIGptImage1Mini(t *testing.T) {
	key := os.Getenv("OPENAI_API_KEY")
	if key == "" {
		t.Skip("OPENAI_API_KEY not set")
	}
	if os.Getenv("LLMKIT_RUN_SLOW_IMAGE") == "" {
		t.Skip("LLMKIT_RUN_SLOW_IMAGE not set; skipping gpt-image-1-mini smoke")
	}
	c := llmkit.New(providers.OpenAI, key)
	resp, err := c.Image.Model("gpt-image-1-mini").Generate(context.Background(), "A simple red circle on a white background.")
	if err != nil {
		t.Fatal(err)
	}
	if len(resp.Images) == 0 {
		t.Fatal("no images returned")
	}
	if len(resp.Images[0].Bytes) == 0 {
		t.Error("first image has zero bytes")
	}
	if resp.Tokens.Output == 0 {
		t.Error("no output tokens reported (image-output tokens should land in candidatesTokenCount)")
	}
}

func TestIntegrationImageOpenAIGptImage15(t *testing.T) {
	key := os.Getenv("OPENAI_API_KEY")
	if key == "" {
		t.Skip("OPENAI_API_KEY not set")
	}
	if os.Getenv("LLMKIT_RUN_SLOW_IMAGE") == "" {
		t.Skip("LLMKIT_RUN_SLOW_IMAGE not set; skipping gpt-image-1.5 smoke")
	}
	c := llmkit.New(providers.OpenAI, key)
	resp, err := c.Image.Model("gpt-image-1.5").Generate(context.Background(), "A simple red circle on a white background.")
	if err != nil {
		t.Fatal(err)
	}
	if len(resp.Images) == 0 {
		t.Fatal("no images returned")
	}
	if len(resp.Images[0].Bytes) == 0 {
		t.Error("first image has zero bytes")
	}
	if resp.Tokens.Output == 0 {
		t.Error("no output tokens reported (image-output tokens should land in candidatesTokenCount)")
	}
}

func TestIntegrationImageOpenAIGptImage2(t *testing.T) {
	key := os.Getenv("OPENAI_API_KEY")
	if key == "" {
		t.Skip("OPENAI_API_KEY not set")
	}
	c := llmkit.New(providers.OpenAI, key)
	resp, err := c.Image.Model("gpt-image-2").Generate(context.Background(), "A simple red circle on a white background.")
	if err != nil {
		t.Fatal(err)
	}
	if len(resp.Images) == 0 {
		t.Fatal("no images returned")
	}
	if len(resp.Images[0].Bytes) == 0 {
		t.Error("first image has zero bytes")
	}
	if resp.Tokens.Output == 0 {
		t.Error("no output tokens reported (image-output tokens should land in candidatesTokenCount)")
	}
}

func TestIntegrationImageRecraftRecraftv3(t *testing.T) {
	key := os.Getenv("RECRAFT_API_TOKEN")
	if key == "" {
		t.Skip("RECRAFT_API_TOKEN not set")
	}
	c := llmkit.New(providers.Recraft, key)
	resp, err := c.Image.Model("recraftv3").Generate(context.Background(), "A simple red circle on a white background.")
	if err != nil {
		t.Fatal(err)
	}
	if len(resp.Images) == 0 {
		t.Fatal("no images returned")
	}
	if len(resp.Images[0].Bytes) == 0 {
		t.Error("first image has zero bytes")
	}
	if resp.Tokens.Output == 0 {
		t.Error("no output tokens reported (image-output tokens should land in candidatesTokenCount)")
	}
}

func TestIntegrationImageRecraftRecraftv3Vector(t *testing.T) {
	key := os.Getenv("RECRAFT_API_TOKEN")
	if key == "" {
		t.Skip("RECRAFT_API_TOKEN not set")
	}
	c := llmkit.New(providers.Recraft, key)
	resp, err := c.Image.Model("recraftv3_vector").Generate(context.Background(), "A simple red circle on a white background.")
	if err != nil {
		t.Fatal(err)
	}
	if len(resp.Images) == 0 {
		t.Fatal("no images returned")
	}
	if len(resp.Images[0].Bytes) == 0 {
		t.Error("first image has zero bytes")
	}
	if resp.Tokens.Output == 0 {
		t.Error("no output tokens reported (image-output tokens should land in candidatesTokenCount)")
	}
}

func TestIntegrationImageVertexImagen30FastGenerate001(t *testing.T) {
	key := os.Getenv("VERTEX_BEARER_TOKEN")
	if key == "" {
		t.Skip("VERTEX_BEARER_TOKEN not set")
	}
	c := llmkit.New(providers.Vertex, key)
	resp, err := c.Image.Model("imagen-3.0-fast-generate-001").AspectRatio("1:1").Generate(context.Background(), "A simple red circle on a white background.")
	if err != nil {
		t.Fatal(err)
	}
	if len(resp.Images) == 0 {
		t.Fatal("no images returned")
	}
	if len(resp.Images[0].Bytes) == 0 {
		t.Error("first image has zero bytes")
	}
	if resp.Tokens.Output == 0 {
		t.Error("no output tokens reported (image-output tokens should land in candidatesTokenCount)")
	}
}

func TestIntegrationImageVertexImagen30Generate002(t *testing.T) {
	key := os.Getenv("VERTEX_BEARER_TOKEN")
	if key == "" {
		t.Skip("VERTEX_BEARER_TOKEN not set")
	}
	c := llmkit.New(providers.Vertex, key)
	resp, err := c.Image.Model("imagen-3.0-generate-002").AspectRatio("1:1").Generate(context.Background(), "A simple red circle on a white background.")
	if err != nil {
		t.Fatal(err)
	}
	if len(resp.Images) == 0 {
		t.Fatal("no images returned")
	}
	if len(resp.Images[0].Bytes) == 0 {
		t.Error("first image has zero bytes")
	}
	if resp.Tokens.Output == 0 {
		t.Error("no output tokens reported (image-output tokens should land in candidatesTokenCount)")
	}
}

func TestIntegrationImageVertexImagen40GeneratePreview0606(t *testing.T) {
	key := os.Getenv("VERTEX_BEARER_TOKEN")
	if key == "" {
		t.Skip("VERTEX_BEARER_TOKEN not set")
	}
	c := llmkit.New(providers.Vertex, key)
	resp, err := c.Image.Model("imagen-4.0-generate-preview-06-06").AspectRatio("1:1").Generate(context.Background(), "A simple red circle on a white background.")
	if err != nil {
		t.Fatal(err)
	}
	if len(resp.Images) == 0 {
		t.Fatal("no images returned")
	}
	if len(resp.Images[0].Bytes) == 0 {
		t.Error("first image has zero bytes")
	}
	if resp.Tokens.Output == 0 {
		t.Error("no output tokens reported (image-output tokens should land in candidatesTokenCount)")
	}
}
