// Code generated by codegen/generate.py; DO NOT EDIT.

package providers

// Image input/output mode discriminators.
const (
	ImageInputInlineParts    = "InlineParts"
	ImageInputMultipartForm  = "MultipartForm"
	ImageInputJSONInlineRefs = "JSONInlineRefs"
	ImageInputJSONPredict    = "JSONPredict"
	ImageOutputBase64Inline  = "Base64Inline"
	ImageOutputURLOrBase64   = "URLOrBase64"
)

// ImageModelDef describes one image-generation model and its whitelisted
// aspect ratios and output sizes. Values are the strings sent to the provider
// (e.g., "16:9", "1K") and surfaced unchanged in the runtime API.
type ImageModelDef struct {
	ModelID      string
	Label        string
	AspectRatios []string
	ImageSizes   []string
}

// ImageGenDef holds one provider's image-generation configuration.
// GenEndpoint and EditEndpoint are forward-compat overrides; empty means
// reuse the provider's main endpoint template (Google).
type ImageGenDef struct {
	InputMode     string // ImageInputInlineParts | ImageInputMultipartForm | ImageInputJSONInlineRefs | ImageInputJSONPredict
	OutputMode    string // ImageOutputBase64Inline | ImageOutputURLOrBase64
	MaxInputCount int    // max reference images per request
	GenEndpoint   string // override; empty = use provider main endpoint
	EditEndpoint  string // override; empty = use GenEndpoint
	Models        []ImageModelDef
}

// ImageGenConfig returns the image-generation config for a provider, or nil
// if the provider does not support image generation.
func ImageGenConfig(provider string) *ImageGenDef {
	switch provider {
	case Google:
		return &ImageGenDef{
			InputMode:     "InlineParts",
			OutputMode:    "Base64Inline",
			MaxInputCount: 14,
			GenEndpoint:   "",
			EditEndpoint:  "",
			Models: []ImageModelDef{
				{
					ModelID:      "gemini-3-pro-image-preview",
					Label:        "Nano Banana Pro",
					AspectRatios: []string{"16:9", "1:1", "21:9", "2:3", "3:2", "3:4", "4:3", "4:5", "5:4", "9:16"},
					ImageSizes:   []string{"1K", "2K", "4K"},
				},
				{
					ModelID:      "gemini-3.1-flash-image-preview",
					Label:        "Nano Banana 2",
					AspectRatios: []string{"16:9", "1:1", "1:4", "1:8", "21:9", "2:3", "3:2", "3:4", "4:1", "4:3", "4:5", "5:4", "8:1", "9:16"},
					ImageSizes:   []string{"1K", "2K", "4K", "512"},
				},
			},
		}
	case Grok:
		return &ImageGenDef{
			InputMode:     "JSONInlineRefs",
			OutputMode:    "Base64Inline",
			MaxInputCount: 16,
			GenEndpoint:   "/v1/images/generations",
			EditEndpoint:  "/v1/images/edits",
			Models: []ImageModelDef{
				{
					ModelID:      "grok-imagine-image-quality",
					Label:        "Grok Imagine Quality",
					AspectRatios: []string{"16:9", "19.5:9", "1:1", "1:2", "20:9", "2:1", "2:3", "3:2", "3:4", "4:3", "9:16", "9:19.5", "9:20", "auto"},
					ImageSizes:   []string{},
				},
			},
		}
	case OpenAI:
		return &ImageGenDef{
			InputMode:     "MultipartForm",
			OutputMode:    "Base64Inline",
			MaxInputCount: 16,
			GenEndpoint:   "/v1/images/generations",
			EditEndpoint:  "/v1/images/edits",
			Models: []ImageModelDef{
				{
					ModelID:      "gpt-image-1",
					Label:        "GPT Image 1",
					AspectRatios: []string{},
					ImageSizes:   []string{},
				},
				{
					ModelID:      "gpt-image-1-mini",
					Label:        "GPT Image 1 Mini",
					AspectRatios: []string{},
					ImageSizes:   []string{},
				},
				{
					ModelID:      "gpt-image-1.5",
					Label:        "GPT Image 1.5",
					AspectRatios: []string{},
					ImageSizes:   []string{},
				},
				{
					ModelID:      "gpt-image-2",
					Label:        "GPT Image 2",
					AspectRatios: []string{},
					ImageSizes:   []string{},
				},
			},
		}
	case Vertex:
		return &ImageGenDef{
			InputMode:     "JSONPredict",
			OutputMode:    "Base64Inline",
			MaxInputCount: 1,
			GenEndpoint:   "",
			EditEndpoint:  "",
			Models: []ImageModelDef{
				{
					ModelID:      "imagen-3.0-fast-generate-001",
					Label:        "Imagen 3 Fast",
					AspectRatios: []string{"16:9", "1:1", "3:4", "4:3", "9:16"},
					ImageSizes:   []string{},
				},
				{
					ModelID:      "imagen-3.0-generate-002",
					Label:        "Imagen 3",
					AspectRatios: []string{"16:9", "1:1", "3:4", "4:3", "9:16"},
					ImageSizes:   []string{},
				},
				{
					ModelID:      "imagen-4.0-generate-preview-06-06",
					Label:        "Imagen 4 Preview",
					AspectRatios: []string{"16:9", "1:1", "3:4", "4:3", "9:16"},
					ImageSizes:   []string{},
				},
			},
		}
	default:
		return nil
	}
}
