// Code generated by codegen/generate.py; DO NOT EDIT.

package providers

// Image input/output mode discriminators.
const (
	ImageInputInlineParts   = "InlineParts"
	ImageInputMultipartForm = "MultipartForm"
	ImageOutputBase64Inline = "Base64Inline"
	ImageOutputURLOrBase64  = "URLOrBase64"
)

// ImageModelDef describes one image-generation model and its whitelisted
// aspect ratios and output sizes. Values are the strings sent to the provider
// (e.g., "16:9", "1K") and surfaced unchanged in the runtime API.
type ImageModelDef struct {
	ModelID      string
	Label        string
	AspectRatios []string
	ImageSizes   []string
}

// ImageGenDef holds one provider's image-generation configuration.
// GenEndpoint and EditEndpoint are forward-compat overrides; empty means
// reuse the provider's main endpoint template (Google).
type ImageGenDef struct {
	InputMode     string // ImageInputInlineParts | ImageInputMultipartForm
	OutputMode    string // ImageOutputBase64Inline | ImageOutputURLOrBase64
	MaxInputCount int    // max reference images per request
	GenEndpoint   string // override; empty = use provider main endpoint
	EditEndpoint  string // override; empty = use GenEndpoint
	Models        []ImageModelDef
}

// ImageGenConfig returns the image-generation config for a provider, or nil
// if the provider does not support image generation.
func ImageGenConfig(provider string) *ImageGenDef {
	switch provider {
	case Google:
		return &ImageGenDef{
			InputMode:     "InlineParts",
			OutputMode:    "Base64Inline",
			MaxInputCount: 14,
			GenEndpoint:   "",
			EditEndpoint:  "",
			Models: []ImageModelDef{
				{
					ModelID:      "gemini-3-pro-image-preview",
					Label:        "Nano Banana Pro",
					AspectRatios: []string{"16:9", "1:1", "21:9", "2:3", "3:2", "3:4", "4:3", "4:5", "5:4", "9:16"},
					ImageSizes:   []string{"1K", "2K", "4K"},
				},
				{
					ModelID:      "gemini-3.1-flash-image-preview",
					Label:        "Nano Banana 2",
					AspectRatios: []string{"16:9", "1:1", "1:4", "1:8", "21:9", "2:3", "3:2", "3:4", "4:1", "4:3", "4:5", "5:4", "8:1", "9:16"},
					ImageSizes:   []string{"1K", "2K", "4K", "512"},
				},
			},
		}
	default:
		return nil
	}
}
