// Code generated by codegen/generate.py; DO NOT EDIT.

//go:build integration

package providers_test

import (
	"context"
	"os"
	"testing"

	"github.com/aktagon/llmkit-go"
	"github.com/aktagon/llmkit-go/providers"
)

func TestIntegrationImageGoogleGemini3ProImagePreview(t *testing.T) {
	key := os.Getenv("GOOGLE_API_KEY")
	if key == "" {
		t.Skip("GOOGLE_API_KEY not set")
	}
	if os.Getenv("LLMKIT_RUN_SLOW_IMAGE") == "" {
		t.Skip("LLMKIT_RUN_SLOW_IMAGE not set; skipping gemini-3-pro-image-preview smoke")
	}
	c := llmkit.New(providers.Google, key)
	resp, err := c.Image.Model("gemini-3-pro-image-preview").AspectRatio("1:1").ImageSize("1K").Generate(context.Background(), "A simple red circle on a white background.")
	if err != nil {
		t.Fatal(err)
	}
	if len(resp.Images) == 0 {
		t.Fatal("no images returned")
	}
	if len(resp.Images[0].Bytes) == 0 {
		t.Error("first image has zero bytes")
	}
	if resp.Tokens.Output == 0 {
		t.Error("no output tokens reported (image-output tokens should land in candidatesTokenCount)")
	}
}

func TestIntegrationImageGoogleGemini31FlashImagePreview(t *testing.T) {
	key := os.Getenv("GOOGLE_API_KEY")
	if key == "" {
		t.Skip("GOOGLE_API_KEY not set")
	}
	c := llmkit.New(providers.Google, key)
	resp, err := c.Image.Model("gemini-3.1-flash-image-preview").AspectRatio("1:1").ImageSize("1K").Generate(context.Background(), "A simple red circle on a white background.")
	if err != nil {
		t.Fatal(err)
	}
	if len(resp.Images) == 0 {
		t.Fatal("no images returned")
	}
	if len(resp.Images[0].Bytes) == 0 {
		t.Error("first image has zero bytes")
	}
	if resp.Tokens.Output == 0 {
		t.Error("no output tokens reported (image-output tokens should land in candidatesTokenCount)")
	}
}
