// Code generated by codegen/generate.py; DO NOT EDIT.

//go:build integration

package providers_test

import (
	"context"
	"os"
	"testing"

	"github.com/aktagon/llmkit-go"
	"github.com/aktagon/llmkit-go/providers"
)

func TestIntegrationAI21(t *testing.T) {
	key := os.Getenv("AI21_API_KEY")
	if key == "" {
		t.Skip("AI21_API_KEY not set")
	}
	c := llmkit.New(providers.AI21, key)
	resp, err := c.Text.System("Reply with only the word pong").Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationAI21Stream(t *testing.T) {
	key := os.Getenv("AI21_API_KEY")
	if key == "" {
		t.Skip("AI21_API_KEY not set")
	}
	var chunks int
	var text string
	c := llmkit.New(providers.AI21, key)
	stream := c.Text.System("Reply with only the word pong").Stream(context.Background(), "ping")
	for chunk, err := range stream.Chunks() {
		if err != nil {
			t.Fatal(err)
		}
		chunks++
		text += chunk
	}
	if text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationAnthropic(t *testing.T) {
	key := os.Getenv("ANTHROPIC_API_KEY")
	if key == "" {
		t.Skip("ANTHROPIC_API_KEY not set")
	}
	c := llmkit.New(providers.Anthropic, key)
	resp, err := c.Text.System("Reply with only the word pong").Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationAnthropicStream(t *testing.T) {
	key := os.Getenv("ANTHROPIC_API_KEY")
	if key == "" {
		t.Skip("ANTHROPIC_API_KEY not set")
	}
	var chunks int
	var text string
	c := llmkit.New(providers.Anthropic, key)
	stream := c.Text.System("Reply with only the word pong").Stream(context.Background(), "ping")
	for chunk, err := range stream.Chunks() {
		if err != nil {
			t.Fatal(err)
		}
		chunks++
		text += chunk
	}
	if text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationAssemblyai(t *testing.T) {
	key := os.Getenv("ASSEMBLYAI_API_KEY")
	if key == "" {
		t.Skip("ASSEMBLYAI_API_KEY not set")
	}
	c := llmkit.New(providers.Assemblyai, key)
	resp, err := c.Text.System("Reply with only the word pong").Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationCerebras(t *testing.T) {
	key := os.Getenv("CEREBRAS_API_KEY")
	if key == "" {
		t.Skip("CEREBRAS_API_KEY not set")
	}
	c := llmkit.New(providers.Cerebras, key)
	resp, err := c.Text.System("Reply with only the word pong").Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationCerebrasStream(t *testing.T) {
	key := os.Getenv("CEREBRAS_API_KEY")
	if key == "" {
		t.Skip("CEREBRAS_API_KEY not set")
	}
	var chunks int
	var text string
	c := llmkit.New(providers.Cerebras, key)
	stream := c.Text.System("Reply with only the word pong").Stream(context.Background(), "ping")
	for chunk, err := range stream.Chunks() {
		if err != nil {
			t.Fatal(err)
		}
		chunks++
		text += chunk
	}
	if text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationCohere(t *testing.T) {
	key := os.Getenv("COHERE_API_KEY")
	if key == "" {
		t.Skip("COHERE_API_KEY not set")
	}
	c := llmkit.New(providers.Cohere, key)
	resp, err := c.Text.System("Reply with only the word pong").Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationCohereStream(t *testing.T) {
	key := os.Getenv("COHERE_API_KEY")
	if key == "" {
		t.Skip("COHERE_API_KEY not set")
	}
	var chunks int
	var text string
	c := llmkit.New(providers.Cohere, key)
	stream := c.Text.System("Reply with only the word pong").Stream(context.Background(), "ping")
	for chunk, err := range stream.Chunks() {
		if err != nil {
			t.Fatal(err)
		}
		chunks++
		text += chunk
	}
	if text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationDeepseek(t *testing.T) {
	key := os.Getenv("DEEPSEEK_API_KEY")
	if key == "" {
		t.Skip("DEEPSEEK_API_KEY not set")
	}
	c := llmkit.New(providers.Deepseek, key)
	resp, err := c.Text.System("Reply with only the word pong").Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationDeepseekStream(t *testing.T) {
	key := os.Getenv("DEEPSEEK_API_KEY")
	if key == "" {
		t.Skip("DEEPSEEK_API_KEY not set")
	}
	var chunks int
	var text string
	c := llmkit.New(providers.Deepseek, key)
	stream := c.Text.System("Reply with only the word pong").Stream(context.Background(), "ping")
	for chunk, err := range stream.Chunks() {
		if err != nil {
			t.Fatal(err)
		}
		chunks++
		text += chunk
	}
	if text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationDoubao(t *testing.T) {
	key := os.Getenv("ARK_API_KEY")
	if key == "" {
		t.Skip("ARK_API_KEY not set")
	}
	c := llmkit.New(providers.Doubao, key)
	resp, err := c.Text.System("Reply with only the word pong").Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationDoubaoStream(t *testing.T) {
	key := os.Getenv("ARK_API_KEY")
	if key == "" {
		t.Skip("ARK_API_KEY not set")
	}
	var chunks int
	var text string
	c := llmkit.New(providers.Doubao, key)
	stream := c.Text.System("Reply with only the word pong").Stream(context.Background(), "ping")
	for chunk, err := range stream.Chunks() {
		if err != nil {
			t.Fatal(err)
		}
		chunks++
		text += chunk
	}
	if text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationErnie(t *testing.T) {
	key := os.Getenv("QIANFAN_API_KEY")
	if key == "" {
		t.Skip("QIANFAN_API_KEY not set")
	}
	c := llmkit.New(providers.Ernie, key)
	resp, err := c.Text.System("Reply with only the word pong").Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationErnieStream(t *testing.T) {
	key := os.Getenv("QIANFAN_API_KEY")
	if key == "" {
		t.Skip("QIANFAN_API_KEY not set")
	}
	var chunks int
	var text string
	c := llmkit.New(providers.Ernie, key)
	stream := c.Text.System("Reply with only the word pong").Stream(context.Background(), "ping")
	for chunk, err := range stream.Chunks() {
		if err != nil {
			t.Fatal(err)
		}
		chunks++
		text += chunk
	}
	if text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationFireworks(t *testing.T) {
	key := os.Getenv("FIREWORKS_API_KEY")
	if key == "" {
		t.Skip("FIREWORKS_API_KEY not set")
	}
	c := llmkit.New(providers.Fireworks, key)
	resp, err := c.Text.System("Reply with only the word pong").Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationFireworksStream(t *testing.T) {
	key := os.Getenv("FIREWORKS_API_KEY")
	if key == "" {
		t.Skip("FIREWORKS_API_KEY not set")
	}
	var chunks int
	var text string
	c := llmkit.New(providers.Fireworks, key)
	stream := c.Text.System("Reply with only the word pong").Stream(context.Background(), "ping")
	for chunk, err := range stream.Chunks() {
		if err != nil {
			t.Fatal(err)
		}
		chunks++
		text += chunk
	}
	if text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationGoogle(t *testing.T) {
	key := os.Getenv("GOOGLE_API_KEY")
	if key == "" {
		t.Skip("GOOGLE_API_KEY not set")
	}
	c := llmkit.New(providers.Google, key)
	resp, err := c.Text.System("Reply with only the word pong").Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationGoogleStream(t *testing.T) {
	key := os.Getenv("GOOGLE_API_KEY")
	if key == "" {
		t.Skip("GOOGLE_API_KEY not set")
	}
	var chunks int
	var text string
	c := llmkit.New(providers.Google, key)
	stream := c.Text.System("Reply with only the word pong").Stream(context.Background(), "ping")
	for chunk, err := range stream.Chunks() {
		if err != nil {
			t.Fatal(err)
		}
		chunks++
		text += chunk
	}
	if text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationGrok(t *testing.T) {
	key := os.Getenv("XAI_API_KEY")
	if key == "" {
		t.Skip("XAI_API_KEY not set")
	}
	c := llmkit.New(providers.Grok, key)
	resp, err := c.Text.System("Reply with only the word pong").Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationGrokStream(t *testing.T) {
	key := os.Getenv("XAI_API_KEY")
	if key == "" {
		t.Skip("XAI_API_KEY not set")
	}
	var chunks int
	var text string
	c := llmkit.New(providers.Grok, key)
	stream := c.Text.System("Reply with only the word pong").Stream(context.Background(), "ping")
	for chunk, err := range stream.Chunks() {
		if err != nil {
			t.Fatal(err)
		}
		chunks++
		text += chunk
	}
	if text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationGroq(t *testing.T) {
	key := os.Getenv("GROQ_API_KEY")
	if key == "" {
		t.Skip("GROQ_API_KEY not set")
	}
	c := llmkit.New(providers.Groq, key)
	resp, err := c.Text.System("Reply with only the word pong").Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationGroqStream(t *testing.T) {
	key := os.Getenv("GROQ_API_KEY")
	if key == "" {
		t.Skip("GROQ_API_KEY not set")
	}
	var chunks int
	var text string
	c := llmkit.New(providers.Groq, key)
	stream := c.Text.System("Reply with only the word pong").Stream(context.Background(), "ping")
	for chunk, err := range stream.Chunks() {
		if err != nil {
			t.Fatal(err)
		}
		chunks++
		text += chunk
	}
	if text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationInworld(t *testing.T) {
	key := os.Getenv("INWORLD_API_KEY")
	if key == "" {
		t.Skip("INWORLD_API_KEY not set")
	}
	c := llmkit.New(providers.Inworld, key)
	resp, err := c.Text.System("Reply with only the word pong").Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationJan(t *testing.T) {
	key := os.Getenv("JAN_API_KEY")
	if key == "" {
		t.Skip("JAN_API_KEY not set")
	}
	c := llmkit.New(providers.Jan, key)
	resp, err := c.Text.System("Reply with only the word pong").Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationJanStream(t *testing.T) {
	key := os.Getenv("JAN_API_KEY")
	if key == "" {
		t.Skip("JAN_API_KEY not set")
	}
	var chunks int
	var text string
	c := llmkit.New(providers.Jan, key)
	stream := c.Text.System("Reply with only the word pong").Stream(context.Background(), "ping")
	for chunk, err := range stream.Chunks() {
		if err != nil {
			t.Fatal(err)
		}
		chunks++
		text += chunk
	}
	if text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationLlamacpp(t *testing.T) {
	key := os.Getenv("LLAMACPP_API_KEY")
	if key == "" {
		t.Skip("LLAMACPP_API_KEY not set")
	}
	c := llmkit.New(providers.Llamacpp, key)
	resp, err := c.Text.System("Reply with only the word pong").Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationLlamacppStream(t *testing.T) {
	key := os.Getenv("LLAMACPP_API_KEY")
	if key == "" {
		t.Skip("LLAMACPP_API_KEY not set")
	}
	var chunks int
	var text string
	c := llmkit.New(providers.Llamacpp, key)
	stream := c.Text.System("Reply with only the word pong").Stream(context.Background(), "ping")
	for chunk, err := range stream.Chunks() {
		if err != nil {
			t.Fatal(err)
		}
		chunks++
		text += chunk
	}
	if text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationMinimax(t *testing.T) {
	key := os.Getenv("MINIMAX_API_KEY")
	if key == "" {
		t.Skip("MINIMAX_API_KEY not set")
	}
	c := llmkit.New(providers.Minimax, key)
	resp, err := c.Text.System("Reply with only the word pong").Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationMinimaxStream(t *testing.T) {
	key := os.Getenv("MINIMAX_API_KEY")
	if key == "" {
		t.Skip("MINIMAX_API_KEY not set")
	}
	var chunks int
	var text string
	c := llmkit.New(providers.Minimax, key)
	stream := c.Text.System("Reply with only the word pong").Stream(context.Background(), "ping")
	for chunk, err := range stream.Chunks() {
		if err != nil {
			t.Fatal(err)
		}
		chunks++
		text += chunk
	}
	if text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationMistral(t *testing.T) {
	key := os.Getenv("MISTRAL_API_KEY")
	if key == "" {
		t.Skip("MISTRAL_API_KEY not set")
	}
	c := llmkit.New(providers.Mistral, key)
	resp, err := c.Text.System("Reply with only the word pong").Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationMistralStream(t *testing.T) {
	key := os.Getenv("MISTRAL_API_KEY")
	if key == "" {
		t.Skip("MISTRAL_API_KEY not set")
	}
	var chunks int
	var text string
	c := llmkit.New(providers.Mistral, key)
	stream := c.Text.System("Reply with only the word pong").Stream(context.Background(), "ping")
	for chunk, err := range stream.Chunks() {
		if err != nil {
			t.Fatal(err)
		}
		chunks++
		text += chunk
	}
	if text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationMoonshot(t *testing.T) {
	key := os.Getenv("MOONSHOT_API_KEY")
	if key == "" {
		t.Skip("MOONSHOT_API_KEY not set")
	}
	c := llmkit.New(providers.Moonshot, key)
	resp, err := c.Text.System("Reply with only the word pong").Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationMoonshotStream(t *testing.T) {
	key := os.Getenv("MOONSHOT_API_KEY")
	if key == "" {
		t.Skip("MOONSHOT_API_KEY not set")
	}
	var chunks int
	var text string
	c := llmkit.New(providers.Moonshot, key)
	stream := c.Text.System("Reply with only the word pong").Stream(context.Background(), "ping")
	for chunk, err := range stream.Chunks() {
		if err != nil {
			t.Fatal(err)
		}
		chunks++
		text += chunk
	}
	if text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationOpenAI(t *testing.T) {
	key := os.Getenv("OPENAI_API_KEY")
	if key == "" {
		t.Skip("OPENAI_API_KEY not set")
	}
	c := llmkit.New(providers.OpenAI, key)
	resp, err := c.Text.System("Reply with only the word pong").Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationOpenAIStream(t *testing.T) {
	key := os.Getenv("OPENAI_API_KEY")
	if key == "" {
		t.Skip("OPENAI_API_KEY not set")
	}
	var chunks int
	var text string
	c := llmkit.New(providers.OpenAI, key)
	stream := c.Text.System("Reply with only the word pong").Stream(context.Background(), "ping")
	for chunk, err := range stream.Chunks() {
		if err != nil {
			t.Fatal(err)
		}
		chunks++
		text += chunk
	}
	if text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationOpenrouter(t *testing.T) {
	key := os.Getenv("OPENROUTER_API_KEY")
	if key == "" {
		t.Skip("OPENROUTER_API_KEY not set")
	}
	c := llmkit.New(providers.Openrouter, key)
	resp, err := c.Text.System("Reply with only the word pong").Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationOpenrouterStream(t *testing.T) {
	key := os.Getenv("OPENROUTER_API_KEY")
	if key == "" {
		t.Skip("OPENROUTER_API_KEY not set")
	}
	var chunks int
	var text string
	c := llmkit.New(providers.Openrouter, key)
	stream := c.Text.System("Reply with only the word pong").Stream(context.Background(), "ping")
	for chunk, err := range stream.Chunks() {
		if err != nil {
			t.Fatal(err)
		}
		chunks++
		text += chunk
	}
	if text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationPerplexity(t *testing.T) {
	key := os.Getenv("PERPLEXITY_API_KEY")
	if key == "" {
		t.Skip("PERPLEXITY_API_KEY not set")
	}
	c := llmkit.New(providers.Perplexity, key)
	resp, err := c.Text.System("Reply with only the word pong").Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationPerplexityStream(t *testing.T) {
	key := os.Getenv("PERPLEXITY_API_KEY")
	if key == "" {
		t.Skip("PERPLEXITY_API_KEY not set")
	}
	var chunks int
	var text string
	c := llmkit.New(providers.Perplexity, key)
	stream := c.Text.System("Reply with only the word pong").Stream(context.Background(), "ping")
	for chunk, err := range stream.Chunks() {
		if err != nil {
			t.Fatal(err)
		}
		chunks++
		text += chunk
	}
	if text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationPixverse(t *testing.T) {
	key := os.Getenv("PIXVERSE_API_KEY")
	if key == "" {
		t.Skip("PIXVERSE_API_KEY not set")
	}
	c := llmkit.New(providers.Pixverse, key)
	resp, err := c.Text.System("Reply with only the word pong").Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationQwen(t *testing.T) {
	key := os.Getenv("DASHSCOPE_API_KEY")
	if key == "" {
		t.Skip("DASHSCOPE_API_KEY not set")
	}
	c := llmkit.New(providers.Qwen, key)
	resp, err := c.Text.System("Reply with only the word pong").Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationQwenStream(t *testing.T) {
	key := os.Getenv("DASHSCOPE_API_KEY")
	if key == "" {
		t.Skip("DASHSCOPE_API_KEY not set")
	}
	var chunks int
	var text string
	c := llmkit.New(providers.Qwen, key)
	stream := c.Text.System("Reply with only the word pong").Stream(context.Background(), "ping")
	for chunk, err := range stream.Chunks() {
		if err != nil {
			t.Fatal(err)
		}
		chunks++
		text += chunk
	}
	if text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationRecraft(t *testing.T) {
	key := os.Getenv("RECRAFT_API_TOKEN")
	if key == "" {
		t.Skip("RECRAFT_API_TOKEN not set")
	}
	c := llmkit.New(providers.Recraft, key)
	resp, err := c.Text.System("Reply with only the word pong").Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationSambanova(t *testing.T) {
	key := os.Getenv("SAMBANOVA_API_KEY")
	if key == "" {
		t.Skip("SAMBANOVA_API_KEY not set")
	}
	c := llmkit.New(providers.Sambanova, key)
	resp, err := c.Text.System("Reply with only the word pong").Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationSambanovaStream(t *testing.T) {
	key := os.Getenv("SAMBANOVA_API_KEY")
	if key == "" {
		t.Skip("SAMBANOVA_API_KEY not set")
	}
	var chunks int
	var text string
	c := llmkit.New(providers.Sambanova, key)
	stream := c.Text.System("Reply with only the word pong").Stream(context.Background(), "ping")
	for chunk, err := range stream.Chunks() {
		if err != nil {
			t.Fatal(err)
		}
		chunks++
		text += chunk
	}
	if text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationTogether(t *testing.T) {
	key := os.Getenv("TOGETHER_API_KEY")
	if key == "" {
		t.Skip("TOGETHER_API_KEY not set")
	}
	c := llmkit.New(providers.Together, key)
	resp, err := c.Text.System("Reply with only the word pong").Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationTogetherStream(t *testing.T) {
	key := os.Getenv("TOGETHER_API_KEY")
	if key == "" {
		t.Skip("TOGETHER_API_KEY not set")
	}
	var chunks int
	var text string
	c := llmkit.New(providers.Together, key)
	stream := c.Text.System("Reply with only the word pong").Stream(context.Background(), "ping")
	for chunk, err := range stream.Chunks() {
		if err != nil {
			t.Fatal(err)
		}
		chunks++
		text += chunk
	}
	if text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationVertex(t *testing.T) {
	key := os.Getenv("VERTEX_BEARER_TOKEN")
	if key == "" {
		t.Skip("VERTEX_BEARER_TOKEN not set")
	}
	c := llmkit.New(providers.Vertex, key)
	resp, err := c.Text.System("Reply with only the word pong").Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationVidu(t *testing.T) {
	key := os.Getenv("VIDU_API_KEY")
	if key == "" {
		t.Skip("VIDU_API_KEY not set")
	}
	c := llmkit.New(providers.Vidu, key)
	resp, err := c.Text.System("Reply with only the word pong").Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationWorkersai(t *testing.T) {
	key := os.Getenv("CLOUDFLARE_API_TOKEN")
	if key == "" {
		t.Skip("CLOUDFLARE_API_TOKEN not set")
	}
	c := llmkit.New(providers.Workersai, key)
	resp, err := c.Text.System("Reply with only the word pong").Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationWorkersaiStream(t *testing.T) {
	key := os.Getenv("CLOUDFLARE_API_TOKEN")
	if key == "" {
		t.Skip("CLOUDFLARE_API_TOKEN not set")
	}
	var chunks int
	var text string
	c := llmkit.New(providers.Workersai, key)
	stream := c.Text.System("Reply with only the word pong").Stream(context.Background(), "ping")
	for chunk, err := range stream.Chunks() {
		if err != nil {
			t.Fatal(err)
		}
		chunks++
		text += chunk
	}
	if text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationYi(t *testing.T) {
	key := os.Getenv("YI_API_KEY")
	if key == "" {
		t.Skip("YI_API_KEY not set")
	}
	c := llmkit.New(providers.Yi, key)
	resp, err := c.Text.System("Reply with only the word pong").Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationYiStream(t *testing.T) {
	key := os.Getenv("YI_API_KEY")
	if key == "" {
		t.Skip("YI_API_KEY not set")
	}
	var chunks int
	var text string
	c := llmkit.New(providers.Yi, key)
	stream := c.Text.System("Reply with only the word pong").Stream(context.Background(), "ping")
	for chunk, err := range stream.Chunks() {
		if err != nil {
			t.Fatal(err)
		}
		chunks++
		text += chunk
	}
	if text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationZhipu(t *testing.T) {
	key := os.Getenv("ZHIPU_API_KEY")
	if key == "" {
		t.Skip("ZHIPU_API_KEY not set")
	}
	c := llmkit.New(providers.Zhipu, key)
	resp, err := c.Text.System("Reply with only the word pong").Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationZhipuStream(t *testing.T) {
	key := os.Getenv("ZHIPU_API_KEY")
	if key == "" {
		t.Skip("ZHIPU_API_KEY not set")
	}
	var chunks int
	var text string
	c := llmkit.New(providers.Zhipu, key)
	stream := c.Text.System("Reply with only the word pong").Stream(context.Background(), "ping")
	for chunk, err := range stream.Chunks() {
		if err != nil {
			t.Fatal(err)
		}
		chunks++
		text += chunk
	}
	if text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationAnthropicCaching(t *testing.T) {
	key := os.Getenv("ANTHROPIC_API_KEY")
	if key == "" {
		t.Skip("ANTHROPIC_API_KEY not set")
	}
	c := llmkit.New(providers.Anthropic, key)
	resp, err := c.Text.System("Reply with only the word pong").Caching().Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	t.Logf("cache_read=%d cache_write=%d", resp.Tokens.CacheRead, resp.Tokens.CacheWrite)
}

func TestIntegrationOpenAICaching(t *testing.T) {
	key := os.Getenv("OPENAI_API_KEY")
	if key == "" {
		t.Skip("OPENAI_API_KEY not set")
	}
	c := llmkit.New(providers.OpenAI, key)
	resp, err := c.Text.System("Reply with only the word pong").Caching().Prompt(context.Background(), "ping")
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	t.Logf("cache_read=%d cache_write=%d", resp.Tokens.CacheRead, resp.Tokens.CacheWrite)
}
