// Code generated by codegen/generate.py; DO NOT EDIT.

//go:build integration

package providers_test

import (
	"context"
	"os"
	"testing"

	"github.com/aktagon/llmkit-go"
	"github.com/aktagon/llmkit-go/providers"
)

func TestIntegrationAi21(t *testing.T) {
	key := os.Getenv("AI21_API_KEY")
	if key == "" {
		t.Skip("AI21_API_KEY not set")
	}
	resp, err := llmkit.Prompt(context.Background(),
		llmkit.Provider{Name: providers.Ai21, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationAi21Stream(t *testing.T) {
	key := os.Getenv("AI21_API_KEY")
	if key == "" {
		t.Skip("AI21_API_KEY not set")
	}
	var chunks int
	resp, err := llmkit.PromptStream(context.Background(),
		llmkit.Provider{Name: providers.Ai21, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
		func(chunk string) { chunks++ },
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationAnthropic(t *testing.T) {
	key := os.Getenv("ANTHROPIC_API_KEY")
	if key == "" {
		t.Skip("ANTHROPIC_API_KEY not set")
	}
	resp, err := llmkit.Prompt(context.Background(),
		llmkit.Provider{Name: providers.Anthropic, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationAnthropicStream(t *testing.T) {
	key := os.Getenv("ANTHROPIC_API_KEY")
	if key == "" {
		t.Skip("ANTHROPIC_API_KEY not set")
	}
	var chunks int
	resp, err := llmkit.PromptStream(context.Background(),
		llmkit.Provider{Name: providers.Anthropic, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
		func(chunk string) { chunks++ },
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationCerebras(t *testing.T) {
	key := os.Getenv("CEREBRAS_API_KEY")
	if key == "" {
		t.Skip("CEREBRAS_API_KEY not set")
	}
	resp, err := llmkit.Prompt(context.Background(),
		llmkit.Provider{Name: providers.Cerebras, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationCerebrasStream(t *testing.T) {
	key := os.Getenv("CEREBRAS_API_KEY")
	if key == "" {
		t.Skip("CEREBRAS_API_KEY not set")
	}
	var chunks int
	resp, err := llmkit.PromptStream(context.Background(),
		llmkit.Provider{Name: providers.Cerebras, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
		func(chunk string) { chunks++ },
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationCohere(t *testing.T) {
	key := os.Getenv("COHERE_API_KEY")
	if key == "" {
		t.Skip("COHERE_API_KEY not set")
	}
	resp, err := llmkit.Prompt(context.Background(),
		llmkit.Provider{Name: providers.Cohere, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationCohereStream(t *testing.T) {
	key := os.Getenv("COHERE_API_KEY")
	if key == "" {
		t.Skip("COHERE_API_KEY not set")
	}
	var chunks int
	resp, err := llmkit.PromptStream(context.Background(),
		llmkit.Provider{Name: providers.Cohere, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
		func(chunk string) { chunks++ },
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationDeepseek(t *testing.T) {
	key := os.Getenv("DEEPSEEK_API_KEY")
	if key == "" {
		t.Skip("DEEPSEEK_API_KEY not set")
	}
	resp, err := llmkit.Prompt(context.Background(),
		llmkit.Provider{Name: providers.Deepseek, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationDeepseekStream(t *testing.T) {
	key := os.Getenv("DEEPSEEK_API_KEY")
	if key == "" {
		t.Skip("DEEPSEEK_API_KEY not set")
	}
	var chunks int
	resp, err := llmkit.PromptStream(context.Background(),
		llmkit.Provider{Name: providers.Deepseek, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
		func(chunk string) { chunks++ },
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationDoubao(t *testing.T) {
	key := os.Getenv("ARK_API_KEY")
	if key == "" {
		t.Skip("ARK_API_KEY not set")
	}
	resp, err := llmkit.Prompt(context.Background(),
		llmkit.Provider{Name: providers.Doubao, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationDoubaoStream(t *testing.T) {
	key := os.Getenv("ARK_API_KEY")
	if key == "" {
		t.Skip("ARK_API_KEY not set")
	}
	var chunks int
	resp, err := llmkit.PromptStream(context.Background(),
		llmkit.Provider{Name: providers.Doubao, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
		func(chunk string) { chunks++ },
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationErnie(t *testing.T) {
	key := os.Getenv("QIANFAN_API_KEY")
	if key == "" {
		t.Skip("QIANFAN_API_KEY not set")
	}
	resp, err := llmkit.Prompt(context.Background(),
		llmkit.Provider{Name: providers.Ernie, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationErnieStream(t *testing.T) {
	key := os.Getenv("QIANFAN_API_KEY")
	if key == "" {
		t.Skip("QIANFAN_API_KEY not set")
	}
	var chunks int
	resp, err := llmkit.PromptStream(context.Background(),
		llmkit.Provider{Name: providers.Ernie, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
		func(chunk string) { chunks++ },
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationFireworks(t *testing.T) {
	key := os.Getenv("FIREWORKS_API_KEY")
	if key == "" {
		t.Skip("FIREWORKS_API_KEY not set")
	}
	resp, err := llmkit.Prompt(context.Background(),
		llmkit.Provider{Name: providers.Fireworks, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationFireworksStream(t *testing.T) {
	key := os.Getenv("FIREWORKS_API_KEY")
	if key == "" {
		t.Skip("FIREWORKS_API_KEY not set")
	}
	var chunks int
	resp, err := llmkit.PromptStream(context.Background(),
		llmkit.Provider{Name: providers.Fireworks, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
		func(chunk string) { chunks++ },
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationGoogle(t *testing.T) {
	key := os.Getenv("GOOGLE_API_KEY")
	if key == "" {
		t.Skip("GOOGLE_API_KEY not set")
	}
	resp, err := llmkit.Prompt(context.Background(),
		llmkit.Provider{Name: providers.Google, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationGoogleStream(t *testing.T) {
	key := os.Getenv("GOOGLE_API_KEY")
	if key == "" {
		t.Skip("GOOGLE_API_KEY not set")
	}
	var chunks int
	resp, err := llmkit.PromptStream(context.Background(),
		llmkit.Provider{Name: providers.Google, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
		func(chunk string) { chunks++ },
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationGrok(t *testing.T) {
	key := os.Getenv("GROK_API_KEY")
	if key == "" {
		t.Skip("GROK_API_KEY not set")
	}
	resp, err := llmkit.Prompt(context.Background(),
		llmkit.Provider{Name: providers.Grok, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationGrokStream(t *testing.T) {
	key := os.Getenv("GROK_API_KEY")
	if key == "" {
		t.Skip("GROK_API_KEY not set")
	}
	var chunks int
	resp, err := llmkit.PromptStream(context.Background(),
		llmkit.Provider{Name: providers.Grok, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
		func(chunk string) { chunks++ },
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationGroq(t *testing.T) {
	key := os.Getenv("GROQ_API_KEY")
	if key == "" {
		t.Skip("GROQ_API_KEY not set")
	}
	resp, err := llmkit.Prompt(context.Background(),
		llmkit.Provider{Name: providers.Groq, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationGroqStream(t *testing.T) {
	key := os.Getenv("GROQ_API_KEY")
	if key == "" {
		t.Skip("GROQ_API_KEY not set")
	}
	var chunks int
	resp, err := llmkit.PromptStream(context.Background(),
		llmkit.Provider{Name: providers.Groq, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
		func(chunk string) { chunks++ },
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationMinimax(t *testing.T) {
	key := os.Getenv("MINIMAX_API_KEY")
	if key == "" {
		t.Skip("MINIMAX_API_KEY not set")
	}
	resp, err := llmkit.Prompt(context.Background(),
		llmkit.Provider{Name: providers.Minimax, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationMinimaxStream(t *testing.T) {
	key := os.Getenv("MINIMAX_API_KEY")
	if key == "" {
		t.Skip("MINIMAX_API_KEY not set")
	}
	var chunks int
	resp, err := llmkit.PromptStream(context.Background(),
		llmkit.Provider{Name: providers.Minimax, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
		func(chunk string) { chunks++ },
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationMistral(t *testing.T) {
	key := os.Getenv("MISTRAL_API_KEY")
	if key == "" {
		t.Skip("MISTRAL_API_KEY not set")
	}
	resp, err := llmkit.Prompt(context.Background(),
		llmkit.Provider{Name: providers.Mistral, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationMistralStream(t *testing.T) {
	key := os.Getenv("MISTRAL_API_KEY")
	if key == "" {
		t.Skip("MISTRAL_API_KEY not set")
	}
	var chunks int
	resp, err := llmkit.PromptStream(context.Background(),
		llmkit.Provider{Name: providers.Mistral, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
		func(chunk string) { chunks++ },
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationMoonshot(t *testing.T) {
	key := os.Getenv("MOONSHOT_API_KEY")
	if key == "" {
		t.Skip("MOONSHOT_API_KEY not set")
	}
	resp, err := llmkit.Prompt(context.Background(),
		llmkit.Provider{Name: providers.Moonshot, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationMoonshotStream(t *testing.T) {
	key := os.Getenv("MOONSHOT_API_KEY")
	if key == "" {
		t.Skip("MOONSHOT_API_KEY not set")
	}
	var chunks int
	resp, err := llmkit.PromptStream(context.Background(),
		llmkit.Provider{Name: providers.Moonshot, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
		func(chunk string) { chunks++ },
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationOpenAI(t *testing.T) {
	key := os.Getenv("OPENAI_API_KEY")
	if key == "" {
		t.Skip("OPENAI_API_KEY not set")
	}
	resp, err := llmkit.Prompt(context.Background(),
		llmkit.Provider{Name: providers.OpenAI, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationOpenAIStream(t *testing.T) {
	key := os.Getenv("OPENAI_API_KEY")
	if key == "" {
		t.Skip("OPENAI_API_KEY not set")
	}
	var chunks int
	resp, err := llmkit.PromptStream(context.Background(),
		llmkit.Provider{Name: providers.OpenAI, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
		func(chunk string) { chunks++ },
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationOpenrouter(t *testing.T) {
	key := os.Getenv("OPENROUTER_API_KEY")
	if key == "" {
		t.Skip("OPENROUTER_API_KEY not set")
	}
	resp, err := llmkit.Prompt(context.Background(),
		llmkit.Provider{Name: providers.Openrouter, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationOpenrouterStream(t *testing.T) {
	key := os.Getenv("OPENROUTER_API_KEY")
	if key == "" {
		t.Skip("OPENROUTER_API_KEY not set")
	}
	var chunks int
	resp, err := llmkit.PromptStream(context.Background(),
		llmkit.Provider{Name: providers.Openrouter, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
		func(chunk string) { chunks++ },
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationPerplexity(t *testing.T) {
	key := os.Getenv("PERPLEXITY_API_KEY")
	if key == "" {
		t.Skip("PERPLEXITY_API_KEY not set")
	}
	resp, err := llmkit.Prompt(context.Background(),
		llmkit.Provider{Name: providers.Perplexity, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationPerplexityStream(t *testing.T) {
	key := os.Getenv("PERPLEXITY_API_KEY")
	if key == "" {
		t.Skip("PERPLEXITY_API_KEY not set")
	}
	var chunks int
	resp, err := llmkit.PromptStream(context.Background(),
		llmkit.Provider{Name: providers.Perplexity, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
		func(chunk string) { chunks++ },
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationQwen(t *testing.T) {
	key := os.Getenv("DASHSCOPE_API_KEY")
	if key == "" {
		t.Skip("DASHSCOPE_API_KEY not set")
	}
	resp, err := llmkit.Prompt(context.Background(),
		llmkit.Provider{Name: providers.Qwen, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationQwenStream(t *testing.T) {
	key := os.Getenv("DASHSCOPE_API_KEY")
	if key == "" {
		t.Skip("DASHSCOPE_API_KEY not set")
	}
	var chunks int
	resp, err := llmkit.PromptStream(context.Background(),
		llmkit.Provider{Name: providers.Qwen, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
		func(chunk string) { chunks++ },
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationSambanova(t *testing.T) {
	key := os.Getenv("SAMBANOVA_API_KEY")
	if key == "" {
		t.Skip("SAMBANOVA_API_KEY not set")
	}
	resp, err := llmkit.Prompt(context.Background(),
		llmkit.Provider{Name: providers.Sambanova, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationSambanovaStream(t *testing.T) {
	key := os.Getenv("SAMBANOVA_API_KEY")
	if key == "" {
		t.Skip("SAMBANOVA_API_KEY not set")
	}
	var chunks int
	resp, err := llmkit.PromptStream(context.Background(),
		llmkit.Provider{Name: providers.Sambanova, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
		func(chunk string) { chunks++ },
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationTogether(t *testing.T) {
	key := os.Getenv("TOGETHER_API_KEY")
	if key == "" {
		t.Skip("TOGETHER_API_KEY not set")
	}
	resp, err := llmkit.Prompt(context.Background(),
		llmkit.Provider{Name: providers.Together, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationTogetherStream(t *testing.T) {
	key := os.Getenv("TOGETHER_API_KEY")
	if key == "" {
		t.Skip("TOGETHER_API_KEY not set")
	}
	var chunks int
	resp, err := llmkit.PromptStream(context.Background(),
		llmkit.Provider{Name: providers.Together, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
		func(chunk string) { chunks++ },
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationYi(t *testing.T) {
	key := os.Getenv("YI_API_KEY")
	if key == "" {
		t.Skip("YI_API_KEY not set")
	}
	resp, err := llmkit.Prompt(context.Background(),
		llmkit.Provider{Name: providers.Yi, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationYiStream(t *testing.T) {
	key := os.Getenv("YI_API_KEY")
	if key == "" {
		t.Skip("YI_API_KEY not set")
	}
	var chunks int
	resp, err := llmkit.PromptStream(context.Background(),
		llmkit.Provider{Name: providers.Yi, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
		func(chunk string) { chunks++ },
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationZhipu(t *testing.T) {
	key := os.Getenv("ZHIPU_API_KEY")
	if key == "" {
		t.Skip("ZHIPU_API_KEY not set")
	}
	resp, err := llmkit.Prompt(context.Background(),
		llmkit.Provider{Name: providers.Zhipu, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if resp.Tokens.Input == 0 {
		t.Error("no input tokens reported")
	}
}

func TestIntegrationZhipuStream(t *testing.T) {
	key := os.Getenv("ZHIPU_API_KEY")
	if key == "" {
		t.Skip("ZHIPU_API_KEY not set")
	}
	var chunks int
	resp, err := llmkit.PromptStream(context.Background(),
		llmkit.Provider{Name: providers.Zhipu, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
		func(chunk string) { chunks++ },
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	if chunks == 0 {
		t.Error("no chunks received")
	}
}

func TestIntegrationAnthropicCaching(t *testing.T) {
	key := os.Getenv("ANTHROPIC_API_KEY")
	if key == "" {
		t.Skip("ANTHROPIC_API_KEY not set")
	}
	resp, err := llmkit.Prompt(context.Background(),
		llmkit.Provider{Name: providers.Anthropic, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
		llmkit.WithCaching(),
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	t.Logf("cache_read=%d cache_creation=%d", resp.Tokens.CacheRead, resp.Tokens.CacheCreation)
}

func TestIntegrationOpenAICaching(t *testing.T) {
	key := os.Getenv("OPENAI_API_KEY")
	if key == "" {
		t.Skip("OPENAI_API_KEY not set")
	}
	resp, err := llmkit.Prompt(context.Background(),
		llmkit.Provider{Name: providers.OpenAI, APIKey: key},
		llmkit.Request{System: "Reply with only the word pong", User: "ping"},
		llmkit.WithCaching(),
	)
	if err != nil {
		t.Fatal(err)
	}
	if resp.Text == "" {
		t.Error("empty response text")
	}
	t.Logf("cache_read=%d cache_creation=%d", resp.Tokens.CacheRead, resp.Tokens.CacheCreation)
}
