// Code generated by codegen/generate.py; DO NOT EDIT.

package providers

import (
	"context"
	"time"
)

// Usage tracks token consumption for an LLM call.
// Fields are driven by llm:TokenDimension instances in the ontology.
// Capability-scoped dimensions (e.g., CacheWrite, Reasoning) are zero
// when the corresponding capability is inactive or unreported.
type Usage struct {
	Input      int // universal
	Output     int // universal
	CacheWrite int // scoped to Caching
	CacheRead  int // scoped to Caching
	Reasoning  int // scoped to Reasoning
}

// MiddlewarePhase indicates when a middleware fires relative to the operation.
type MiddlewarePhase string

const (
	// PhasePre — Fires before operation; non-nil return aborts and propagates to caller.
	PhasePre MiddlewarePhase = "pre"
	// PhasePost — Fires after operation completes or errors; return value ignored.
	PhasePost MiddlewarePhase = "post"
)

// MiddlewareOp discriminates which operation the event describes.
type MiddlewareOp string

const (
	// OpLLMRequest — One-shot or streaming LLM request (Prompt, PromptStream).
	OpLLMRequest MiddlewareOp = "llm_request"
	// OpToolCall — Agent invoking a registered Tool with LLM-provided args.
	OpToolCall MiddlewareOp = "tool_call"
	// OpCacheCreate — Provider pre-flight to create a cached resource (e.g., Google /cachedContents).
	OpCacheCreate MiddlewareOp = "cache_create"
	// OpUpload — File upload via UploadFile.
	OpUpload MiddlewareOp = "upload"
	// OpBatchSubmit — Submitting a batch of requests.
	OpBatchSubmit MiddlewareOp = "batch_submit"
)

// Event carries middleware observation and veto data. Field population is
// sparse: only fields relevant to (Op, Phase) are non-zero.
type Event struct {
	// Op — Always set.
	Op MiddlewareOp
	// Phase — Always set.
	Phase MiddlewarePhase
	// Provider — Always set.
	Provider string
	// Model — Always set.
	Model string
	// Tool — Only set when Op=tool_call.
	Tool string
	// Args — Only set when Op=tool_call, Phase=pre. Mutation by middleware is observed by the tool.
	Args map[string]any
	// Result — Only set when Op=tool_call, Phase=post.
	Result string
	// Usage — Set for Op=llm_request, Phase=post.
	Usage Usage
	// Err — Set in Phase=post when the operation failed.
	Err error
	// Duration — Set in Phase=post.
	Duration time.Duration
}

// MiddlewareFn is the user-supplied pre/post hook. Pre-phase non-nil error
// vetoes the operation; post-phase return value is ignored.
type MiddlewareFn func(ctx context.Context, e Event) error
