// Code generated by codegen/generate.py; DO NOT EDIT.

// Live-catalogue response parsers (ADR-019). Each function maps one
// provider wire shape to a typed []ParsedModelRecord. Capabilities
// enrichment from the ontology table lives one layer up in the
// hand-coded runtime — these parsers populate only wire-provided
// fields.

package providers

import (
	"encoding/json"
	"fmt"
	"time"
)

// ParsedModelRecord carries the wire-provided fields for one model.
// The hand-coded runtime maps it into the public ModelInfo by attaching
// Provider, Capabilities (ontology), and (when .Raw() was in the chain)
// the parsed-Raw blob.
type ParsedModelRecord struct {
	ID            string
	DisplayName   string
	Description   string
	Created       int64
	ContextWindow int
	MaxOutput     int
	Raw           json.RawMessage
}

// ParsedModelsPage is the outcome of one HTTP response. NextCursor is
// "" when there are no more pages; the runtime stops paginating then.
// Pagination shape depends on the provider — Anthropic uses last_id,
// Google uses nextPageToken, OpenAI is non-paginated and always returns
// "".
type ParsedModelsPage struct {
	Records    []ParsedModelRecord
	NextCursor string
}

// ParseAnthropicModelsResponse decodes the cursor-paginated Anthropic
// /v1/models response. NextCursor reads from last_id when has_more is
// true; empty otherwise.
func ParseAnthropicModelsResponse(body []byte) (ParsedModelsPage, error) {
	var envelope struct {
		Data    []json.RawMessage `json:"data"`
		HasMore bool              `json:"has_more"`
		LastID  string            `json:"last_id"`
	}
	if err := json.Unmarshal(body, &envelope); err != nil {
		return ParsedModelsPage{}, fmt.Errorf("anthropic models: decode envelope: %w", err)
	}
	records := make([]ParsedModelRecord, 0, len(envelope.Data))
	for i, raw := range envelope.Data {
		var wire struct {
			ID              string `json:"id"`
			DisplayName     string `json:"display_name"`
			CreatedAt       string `json:"created_at"`
			MaxInputTokens  int    `json:"max_input_tokens"`
			MaxOutputTokens int    `json:"max_output_tokens"`
			MaxTokens       int    `json:"max_tokens"`
		}
		if err := json.Unmarshal(raw, &wire); err != nil {
			return ParsedModelsPage{}, fmt.Errorf("anthropic models: decode record %d: %w", i, err)
		}
		maxOut := wire.MaxOutputTokens
		if maxOut == 0 {
			maxOut = wire.MaxTokens
		}
		records = append(records, ParsedModelRecord{
			ID:            wire.ID,
			DisplayName:   wire.DisplayName,
			ContextWindow: wire.MaxInputTokens,
			MaxOutput:     maxOut,
			Created:       parseISO8601Best(wire.CreatedAt),
			Raw:           raw,
		})
	}
	next := ""
	if envelope.HasMore {
		next = envelope.LastID
	}
	return ParsedModelsPage{Records: records, NextCursor: next}, nil
}

// ParseOpenAICohortModelsResponse decodes the non-paginated OpenAI
// /v1/models response (and any provider that mirrors the shape — xAI
// Grok, Cerebras, Groq, Together, etc.). NextCursor is always "".
func ParseOpenAICohortModelsResponse(body []byte) (ParsedModelsPage, error) {
	var envelope struct {
		Data []json.RawMessage `json:"data"`
	}
	if err := json.Unmarshal(body, &envelope); err != nil {
		return ParsedModelsPage{}, fmt.Errorf("openai-cohort models: decode envelope: %w", err)
	}
	records := make([]ParsedModelRecord, 0, len(envelope.Data))
	for i, raw := range envelope.Data {
		var wire struct {
			ID      string `json:"id"`
			Created int64  `json:"created"`
		}
		if err := json.Unmarshal(raw, &wire); err != nil {
			return ParsedModelsPage{}, fmt.Errorf("openai-cohort models: decode record %d: %w", i, err)
		}
		records = append(records, ParsedModelRecord{
			ID:      wire.ID,
			Created: wire.Created,
			Raw:     raw,
		})
	}
	return ParsedModelsPage{Records: records, NextCursor: ""}, nil
}

// ParseGoogleModelsResponse decodes the cursor-paginated Google
// /v1beta/models response. The wire "name" field carries a "models/"
// prefix that is stripped before populating ParsedModelRecord.ID so
// the SDK round-trips raw model IDs.
func ParseGoogleModelsResponse(body []byte) (ParsedModelsPage, error) {
	var envelope struct {
		Models        []json.RawMessage `json:"models"`
		NextPageToken string            `json:"nextPageToken"`
	}
	if err := json.Unmarshal(body, &envelope); err != nil {
		return ParsedModelsPage{}, fmt.Errorf("google models: decode envelope: %w", err)
	}
	records := make([]ParsedModelRecord, 0, len(envelope.Models))
	for i, raw := range envelope.Models {
		var wire struct {
			Name             string `json:"name"`
			DisplayName      string `json:"displayName"`
			Description      string `json:"description"`
			InputTokenLimit  int    `json:"inputTokenLimit"`
			OutputTokenLimit int    `json:"outputTokenLimit"`
		}
		if err := json.Unmarshal(raw, &wire); err != nil {
			return ParsedModelsPage{}, fmt.Errorf("google models: decode record %d: %w", i, err)
		}
		id := wire.Name
		const prefix = "models/"
		if len(id) > len(prefix) && id[:len(prefix)] == prefix {
			id = id[len(prefix):]
		}
		records = append(records, ParsedModelRecord{
			ID:            id,
			DisplayName:   wire.DisplayName,
			Description:   wire.Description,
			ContextWindow: wire.InputTokenLimit,
			MaxOutput:     wire.OutputTokenLimit,
			Raw:           raw,
		})
	}
	return ParsedModelsPage{Records: records, NextCursor: envelope.NextPageToken}, nil
}

// parseISO8601Best returns a Unix timestamp for the YYYY-MM-DDTHH:MM:SSZ
// shape Anthropic uses for created_at. Returns 0 on parse failure —
// catalogue records do not depend on Created for correctness.
func parseISO8601Best(s string) int64 {
	if s == "" {
		return 0
	}
	t, err := time.Parse(time.RFC3339, s)
	if err != nil {
		return 0
	}
	return t.Unix()
}
