// Code generated by codegen/generate.py; DO NOT EDIT.

package providers

// Music wire-shape discriminators. Each fully determines the request
// body, the response audio path, AND the byte encoding (base64 vs hex).
const (
	MusicShapePredict         = "MusicPredict"
	MusicShapeGenerateContent = "MusicGenerateContent"
	MusicShapeMinimax         = "MusicMinimax"
)

// MusicModelDef describes one music-generation model. MaxDurationSeconds
// is 0 when the provider documents no fixed ceiling (MiniMax).
type MusicModelDef struct {
	ModelID            string
	Label              string
	SupportsLyrics     bool
	MaxDurationSeconds int
	OutputMime         string
	// SampleRateHz + AvailableOutputFormats are ADR-037 advisory facts
	// (queryable, never gated). SampleRateHz is 0 when unverified.
	SampleRateHz           int
	AvailableOutputFormats []string
}

// MusicGenDef holds one provider's music-generation configuration.
// GenEndpoint is an override; empty means reuse the provider's main
// endpoint template (Vertex :predict, Gemini :generateContent).
type MusicGenDef struct {
	WireShape   string // MusicShapePredict | MusicShapeGenerateContent | MusicShapeMinimax
	GenEndpoint string // override; empty = use provider main endpoint
	Models      []MusicModelDef
}

// MusicGenConfig returns the music-generation config for a provider, or nil
// if the provider does not support music generation.
func MusicGenConfig(provider string) *MusicGenDef {
	switch provider {
	case Google:
		return &MusicGenDef{
			WireShape:   "MusicGenerateContent",
			GenEndpoint: "",
			Models: []MusicModelDef{
				{
					ModelID:                "lyria-3-clip-preview",
					Label:                  "Lyria 3 Clip",
					SupportsLyrics:         true,
					MaxDurationSeconds:     30,
					OutputMime:             "audio/mpeg",
					SampleRateHz:           0,
					AvailableOutputFormats: []string{"audio/mpeg"},
				},
				{
					ModelID:                "lyria-3-pro-preview",
					Label:                  "Lyria 3 Pro",
					SupportsLyrics:         true,
					MaxDurationSeconds:     120,
					OutputMime:             "audio/mpeg",
					SampleRateHz:           0,
					AvailableOutputFormats: []string{"audio/mpeg"},
				},
			},
		}
	case Minimax:
		return &MusicGenDef{
			WireShape:   "MusicMinimax",
			GenEndpoint: "https://api.minimax.io/v1/music_generation",
			Models: []MusicModelDef{
				{
					ModelID:                "music-2.6",
					Label:                  "MiniMax Music 2.6",
					SupportsLyrics:         true,
					MaxDurationSeconds:     0,
					OutputMime:             "audio/mpeg",
					SampleRateHz:           44100,
					AvailableOutputFormats: []string{"audio/mpeg", "audio/wav"},
				},
			},
		}
	case Vertex:
		return &MusicGenDef{
			WireShape:   "MusicPredict",
			GenEndpoint: "",
			Models: []MusicModelDef{
				{
					ModelID:                "lyria-002",
					Label:                  "Lyria 2",
					SupportsLyrics:         false,
					MaxDurationSeconds:     30,
					OutputMime:             "audio/wav",
					SampleRateHz:           48000,
					AvailableOutputFormats: []string{"audio/wav"},
				},
			},
		}
	default:
		return nil
	}
}
