// Code generated by codegen/generate.py; DO NOT EDIT.

package providers

// OptionKey identifies a generation parameter.
type OptionKey string

const (
	OptionFrequencyPenalty OptionKey = "frequency_penalty"
	OptionMaxTokens        OptionKey = "max_tokens"
	OptionPresencePenalty  OptionKey = "presence_penalty"
	OptionReasoningEffort  OptionKey = "reasoning_effort"
	OptionSeed             OptionKey = "seed"
	OptionStopSequences    OptionKey = "stop_sequences"
	OptionTemperature      OptionKey = "temperature"
	OptionThinkingBudget   OptionKey = "thinking_budget"
	OptionTopK             OptionKey = "top_k"
	OptionTopP             OptionKey = "top_p"
)

// OptionDef describes a generation parameter.
type OptionDef struct {
	Key     OptionKey
	GoType  string
	JSONKey string
}

// OptionOverrideDef holds extended override details for a provider option.
type OptionOverrideDef struct {
	JSONKey         string // provider-specific JSON key (may be dotted for nesting)
	AllowedValues   string // CSV of valid values (empty = no constraint)
	ExtraFields     string // JSON of static sibling fields (empty = none)
	RootExtraFields string // JSON deep-merged at the body root when set (ADR-029; empty = none)
}

// AllOptions returns definitions for all known generation parameters.
func AllOptions() []OptionDef {
	return []OptionDef{
		{Key: OptionFrequencyPenalty, GoType: "float64", JSONKey: "frequency_penalty"},
		{Key: OptionMaxTokens, GoType: "int", JSONKey: "max_tokens"},
		{Key: OptionPresencePenalty, GoType: "float64", JSONKey: "presence_penalty"},
		{Key: OptionReasoningEffort, GoType: "string", JSONKey: "reasoning_effort"},
		{Key: OptionSeed, GoType: "int64", JSONKey: "seed"},
		{Key: OptionStopSequences, GoType: "[]string", JSONKey: "stop_sequences"},
		{Key: OptionTemperature, GoType: "float64", JSONKey: "temperature"},
		{Key: OptionThinkingBudget, GoType: "int", JSONKey: "thinking_budget"},
		{Key: OptionTopK, GoType: "int", JSONKey: "top_k"},
		{Key: OptionTopP, GoType: "float64", JSONKey: "top_p"},
	}
}

// SupportedOptions returns the set of supported option keys for a provider,
// with provider-specific JSON key overrides applied.
func SupportedOptions(provider string) map[OptionKey]string {
	switch ProviderName(provider) {
	case AI21:
		return map[OptionKey]string{
			OptionMaxTokens:     "max_tokens",
			OptionStopSequences: "stop",
			OptionTemperature:   "temperature",
			OptionTopP:          "top_p",
		}
	case Anthropic:
		return map[OptionKey]string{
			OptionMaxTokens:       "max_tokens",
			OptionReasoningEffort: "output_config.effort",
			OptionStopSequences:   "stop_sequences",
			OptionTemperature:     "temperature",
			OptionThinkingBudget:  "thinking.budget_tokens",
			OptionTopK:            "top_k",
			OptionTopP:            "top_p",
		}
	case Azure:
		return map[OptionKey]string{
			OptionFrequencyPenalty: "frequency_penalty",
			OptionMaxTokens:        "max_tokens",
			OptionPresencePenalty:  "presence_penalty",
			OptionSeed:             "seed",
			OptionStopSequences:    "stop",
			OptionTemperature:      "temperature",
			OptionTopP:             "top_p",
		}
	case Bedrock:
		return map[OptionKey]string{
			OptionMaxTokens:     "maxTokens",
			OptionStopSequences: "stopSequences",
			OptionTemperature:   "temperature",
			OptionTopP:          "top_p",
		}
	case Cerebras:
		return map[OptionKey]string{
			OptionMaxTokens:     "max_tokens",
			OptionSeed:          "seed",
			OptionStopSequences: "stop",
			OptionTemperature:   "temperature",
			OptionTopP:          "top_p",
		}
	case Cohere:
		return map[OptionKey]string{
			OptionFrequencyPenalty: "frequency_penalty",
			OptionMaxTokens:        "max_tokens",
			OptionPresencePenalty:  "presence_penalty",
			OptionSeed:             "seed",
			OptionStopSequences:    "stop",
			OptionTemperature:      "temperature",
			OptionTopK:             "top_k",
			OptionTopP:             "top_p",
		}
	case Deepseek:
		return map[OptionKey]string{
			OptionFrequencyPenalty: "frequency_penalty",
			OptionMaxTokens:        "max_tokens",
			OptionPresencePenalty:  "presence_penalty",
			OptionStopSequences:    "stop",
			OptionTemperature:      "temperature",
			OptionTopP:             "top_p",
		}
	case Doubao:
		return map[OptionKey]string{
			OptionFrequencyPenalty: "frequency_penalty",
			OptionMaxTokens:        "max_tokens",
			OptionPresencePenalty:  "presence_penalty",
			OptionStopSequences:    "stop",
			OptionTemperature:      "temperature",
			OptionTopP:             "top_p",
		}
	case Ernie:
		return map[OptionKey]string{
			OptionFrequencyPenalty: "frequency_penalty",
			OptionMaxTokens:        "max_tokens",
			OptionPresencePenalty:  "presence_penalty",
			OptionStopSequences:    "stop",
			OptionTemperature:      "temperature",
			OptionTopP:             "top_p",
		}
	case Fireworks:
		return map[OptionKey]string{
			OptionFrequencyPenalty: "frequency_penalty",
			OptionMaxTokens:        "max_tokens",
			OptionPresencePenalty:  "presence_penalty",
			OptionStopSequences:    "stop",
			OptionTemperature:      "temperature",
			OptionTopK:             "top_k",
			OptionTopP:             "top_p",
		}
	case Google:
		return map[OptionKey]string{
			OptionMaxTokens:       "max_output_tokens",
			OptionReasoningEffort: "thinkingConfig.thinkingLevel",
			OptionSeed:            "seed",
			OptionStopSequences:   "stop_sequences",
			OptionTemperature:     "temperature",
			OptionThinkingBudget:  "thinkingConfig.thinkingBudget",
			OptionTopK:            "top_k",
			OptionTopP:            "top_p",
		}
	case Grok:
		return map[OptionKey]string{
			OptionFrequencyPenalty: "frequency_penalty",
			OptionMaxTokens:        "max_tokens",
			OptionPresencePenalty:  "presence_penalty",
			OptionSeed:             "seed",
			OptionStopSequences:    "stop",
			OptionTemperature:      "temperature",
			OptionTopK:             "top_k",
			OptionTopP:             "top_p",
		}
	case Groq:
		return map[OptionKey]string{
			OptionFrequencyPenalty: "frequency_penalty",
			OptionMaxTokens:        "max_tokens",
			OptionPresencePenalty:  "presence_penalty",
			OptionSeed:             "seed",
			OptionStopSequences:    "stop",
			OptionTemperature:      "temperature",
			OptionTopP:             "top_p",
		}
	case Jan:
		return map[OptionKey]string{
			OptionMaxTokens:     "max_tokens",
			OptionSeed:          "seed",
			OptionStopSequences: "stop",
			OptionTemperature:   "temperature",
			OptionTopK:          "top_k",
			OptionTopP:          "top_p",
		}
	case Llamacpp:
		return map[OptionKey]string{
			OptionMaxTokens:     "max_tokens",
			OptionSeed:          "seed",
			OptionStopSequences: "stop",
			OptionTemperature:   "temperature",
			OptionTopK:          "top_k",
			OptionTopP:          "top_p",
		}
	case Lmstudio:
		return map[OptionKey]string{
			OptionMaxTokens:     "max_tokens",
			OptionSeed:          "seed",
			OptionStopSequences: "stop",
			OptionTemperature:   "temperature",
			OptionTopP:          "top_p",
		}
	case Minimax:
		return map[OptionKey]string{
			OptionMaxTokens:     "max_tokens",
			OptionStopSequences: "stop",
			OptionTemperature:   "temperature",
			OptionTopP:          "top_p",
		}
	case Mistral:
		return map[OptionKey]string{
			OptionMaxTokens:     "max_tokens",
			OptionSeed:          "seed",
			OptionStopSequences: "stop",
			OptionTemperature:   "temperature",
			OptionTopP:          "top_p",
		}
	case Moonshot:
		return map[OptionKey]string{
			OptionMaxTokens:     "max_tokens",
			OptionStopSequences: "stop",
			OptionTemperature:   "temperature",
			OptionTopP:          "top_p",
		}
	case Ollama:
		return map[OptionKey]string{
			OptionMaxTokens:     "max_tokens",
			OptionSeed:          "seed",
			OptionStopSequences: "stop",
			OptionTemperature:   "temperature",
			OptionTopK:          "top_k",
			OptionTopP:          "top_p",
		}
	case OpenAI:
		return map[OptionKey]string{
			OptionFrequencyPenalty: "frequency_penalty",
			OptionMaxTokens:        "max_tokens",
			OptionPresencePenalty:  "presence_penalty",
			OptionReasoningEffort:  "reasoning_effort",
			OptionSeed:             "seed",
			OptionStopSequences:    "stop",
			OptionTemperature:      "temperature",
			OptionTopP:             "top_p",
		}
	case Openrouter:
		return map[OptionKey]string{
			OptionFrequencyPenalty: "frequency_penalty",
			OptionMaxTokens:        "max_tokens",
			OptionPresencePenalty:  "presence_penalty",
			OptionSeed:             "seed",
			OptionStopSequences:    "stop",
			OptionTemperature:      "temperature",
			OptionTopK:             "top_k",
			OptionTopP:             "top_p",
		}
	case Perplexity:
		return map[OptionKey]string{
			OptionFrequencyPenalty: "frequency_penalty",
			OptionMaxTokens:        "max_tokens",
			OptionPresencePenalty:  "presence_penalty",
			OptionTemperature:      "temperature",
			OptionTopP:             "top_p",
		}
	case Qwen:
		return map[OptionKey]string{
			OptionMaxTokens:     "max_tokens",
			OptionSeed:          "seed",
			OptionStopSequences: "stop",
			OptionTemperature:   "temperature",
			OptionTopK:          "top_k",
			OptionTopP:          "top_p",
		}
	case Sambanova:
		return map[OptionKey]string{
			OptionMaxTokens:     "max_tokens",
			OptionStopSequences: "stop",
			OptionTemperature:   "temperature",
			OptionTopP:          "top_p",
		}
	case Together:
		return map[OptionKey]string{
			OptionFrequencyPenalty: "frequency_penalty",
			OptionMaxTokens:        "max_tokens",
			OptionPresencePenalty:  "presence_penalty",
			OptionSeed:             "seed",
			OptionStopSequences:    "stop",
			OptionTemperature:      "temperature",
			OptionTopK:             "top_k",
			OptionTopP:             "top_p",
		}
	case Vertex:
		return map[OptionKey]string{
			OptionMaxTokens: "max_tokens",
		}
	case Vllm:
		return map[OptionKey]string{
			OptionFrequencyPenalty: "frequency_penalty",
			OptionMaxTokens:        "max_tokens",
			OptionPresencePenalty:  "presence_penalty",
			OptionSeed:             "seed",
			OptionStopSequences:    "stop",
			OptionTemperature:      "temperature",
			OptionTopK:             "top_k",
			OptionTopP:             "top_p",
		}
	case Workersai:
		return map[OptionKey]string{
			OptionMaxTokens:   "max_tokens",
			OptionTemperature: "temperature",
			OptionTopP:        "top_p",
		}
	case Yi:
		return map[OptionKey]string{
			OptionMaxTokens:     "max_tokens",
			OptionStopSequences: "stop",
			OptionTemperature:   "temperature",
			OptionTopP:          "top_p",
		}
	case Zhipu:
		return map[OptionKey]string{
			OptionMaxTokens:     "max_tokens",
			OptionStopSequences: "stop",
			OptionTemperature:   "temperature",
			OptionTopP:          "top_p",
		}
	default:
		return nil
	}
}

// OptionOverrides returns extended override details for provider options that have them.
// Only options with allowedValues or extraFields are included.
func OptionOverrides(provider string) map[OptionKey]OptionOverrideDef {
	switch ProviderName(provider) {
	case Anthropic:
		return map[OptionKey]OptionOverrideDef{
			OptionReasoningEffort: {
				JSONKey:         "output_config.effort",
				AllowedValues:   "low,medium,high,xhigh,max",
				ExtraFields:     ``,
				RootExtraFields: `{"thinking":{"type":"adaptive"}}`,
			},
			OptionThinkingBudget: {
				JSONKey:         "thinking.budget_tokens",
				AllowedValues:   "",
				ExtraFields:     `{"type":"enabled"}`,
				RootExtraFields: ``,
			},
		}
	case Google:
		return map[OptionKey]OptionOverrideDef{
			OptionReasoningEffort: {
				JSONKey:         "thinkingConfig.thinkingLevel",
				AllowedValues:   "low,high",
				ExtraFields:     ``,
				RootExtraFields: ``,
			},
		}
	case OpenAI:
		return map[OptionKey]OptionOverrideDef{
			OptionReasoningEffort: {
				JSONKey:         "reasoning_effort",
				AllowedValues:   "low,medium,high",
				ExtraFields:     ``,
				RootExtraFields: ``,
			},
		}
	default:
		return nil
	}
}

// ModelOptionOverrideDef is one per-model wire-key override (ADR-024).
// MatcherKind is "id" (exact ModelID) or "pattern" (literal prefix + trailing '*').
type ModelOptionOverrideDef struct {
	MatcherKind  string
	MatcherValue string
	Key          OptionKey
	JSONKey      string
}

// ModelOptionOverrides returns per-model wire-key overrides for a provider,
// in precedence order (exact ids first, then longest-prefix globs).
func ModelOptionOverrides(provider string) []ModelOptionOverrideDef {
	switch ProviderName(provider) {
	case OpenAI:
		return []ModelOptionOverrideDef{
			{MatcherKind: "pattern", MatcherValue: "gpt-5*", Key: OptionMaxTokens, JSONKey: "max_completion_tokens"},
			{MatcherKind: "pattern", MatcherValue: "o*", Key: OptionMaxTokens, JSONKey: "max_completion_tokens"},
		}
	default:
		return nil
	}
}
