// Code generated by codegen/generate.py; DO NOT EDIT.

package providers

import "sort"

// ProviderInfo is WHAT a user wants to know about a provider (PUBLIC): the
// narrow, stable catalogue (typed identity, env var, default model, base
// URL). It is a projection of the same provider facts that feed the internal
// providerSpec, so the two cannot drift.
type ProviderInfo struct {
	ID           ProviderName // typed identity (ADR-040)
	Slug         string       // the slug; equal to string(ID)
	EnvVar       string
	DefaultModel string
	BaseURL      string
}

// Info returns the public metadata for a provider. Keyed by the typed
// identity, it is honestly total — every ProviderName has metadata
// (ADR-040 PSR-001).
func Info(id ProviderName) ProviderInfo {
	return providerInfoTable[id]
}

// List returns the public metadata for every provider, sorted by slug.
func List() []ProviderInfo {
	out := make([]ProviderInfo, 0, len(providerInfoTable))
	for _, info := range providerInfoTable {
		out = append(out, info)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Slug < out[j].Slug })
	return out
}

var providerInfoTable = map[ProviderName]ProviderInfo{
	AI21: {
		ID:           AI21,
		Slug:         "ai21",
		EnvVar:       "AI21_API_KEY",
		DefaultModel: "jamba-1.5-large",
		BaseURL:      "https://api.ai21.com",
	},
	Anthropic: {
		ID:           Anthropic,
		Slug:         "anthropic",
		EnvVar:       "ANTHROPIC_API_KEY",
		DefaultModel: "claude-sonnet-4-6",
		BaseURL:      "https://api.anthropic.com",
	},
	Azure: {
		ID:           Azure,
		Slug:         "azure",
		EnvVar:       "AZURE_OPENAI_API_KEY",
		DefaultModel: "gpt-4o",
		BaseURL:      "https://REPLACE-WITH-YOUR-RESOURCE.openai.azure.com",
	},
	Bedrock: {
		ID:           Bedrock,
		Slug:         "bedrock",
		EnvVar:       "AWS_ACCESS_KEY_ID",
		DefaultModel: "anthropic.claude-sonnet-4-20250514-v1:0",
		BaseURL:      "https://bedrock-runtime.{region}.amazonaws.com",
	},
	Cerebras: {
		ID:           Cerebras,
		Slug:         "cerebras",
		EnvVar:       "CEREBRAS_API_KEY",
		DefaultModel: "llama-3.3-70b",
		BaseURL:      "https://api.cerebras.ai",
	},
	Cohere: {
		ID:           Cohere,
		Slug:         "cohere",
		EnvVar:       "COHERE_API_KEY",
		DefaultModel: "command-r-plus",
		BaseURL:      "https://api.cohere.com/compatibility",
	},
	Deepseek: {
		ID:           Deepseek,
		Slug:         "deepseek",
		EnvVar:       "DEEPSEEK_API_KEY",
		DefaultModel: "deepseek-chat",
		BaseURL:      "https://api.deepseek.com",
	},
	Doubao: {
		ID:           Doubao,
		Slug:         "doubao",
		EnvVar:       "ARK_API_KEY",
		DefaultModel: "doubao-1.5-pro-32k-250115",
		BaseURL:      "https://ark.cn-beijing.volces.com/api/v3",
	},
	Ernie: {
		ID:           Ernie,
		Slug:         "ernie",
		EnvVar:       "QIANFAN_API_KEY",
		DefaultModel: "ernie-4.0-8k",
		BaseURL:      "https://qianfan.baidubce.com/v2",
	},
	Fireworks: {
		ID:           Fireworks,
		Slug:         "fireworks",
		EnvVar:       "FIREWORKS_API_KEY",
		DefaultModel: "accounts/fireworks/models/llama-v3p3-70b-instruct",
		BaseURL:      "https://api.fireworks.ai/inference",
	},
	Google: {
		ID:           Google,
		Slug:         "google",
		EnvVar:       "GOOGLE_API_KEY",
		DefaultModel: "gemini-2.5-flash",
		BaseURL:      "https://generativelanguage.googleapis.com",
	},
	Grok: {
		ID:           Grok,
		Slug:         "grok",
		EnvVar:       "XAI_API_KEY",
		DefaultModel: "grok-3-fast",
		BaseURL:      "https://api.x.ai",
	},
	Groq: {
		ID:           Groq,
		Slug:         "groq",
		EnvVar:       "GROQ_API_KEY",
		DefaultModel: "llama-3.3-70b-versatile",
		BaseURL:      "https://api.groq.com/openai",
	},
	Jan: {
		ID:           Jan,
		Slug:         "jan",
		EnvVar:       "JAN_API_KEY",
		DefaultModel: "",
		BaseURL:      "http://localhost:1337",
	},
	Llamacpp: {
		ID:           Llamacpp,
		Slug:         "llamacpp",
		EnvVar:       "LLAMACPP_API_KEY",
		DefaultModel: "",
		BaseURL:      "http://localhost:8080",
	},
	Lmstudio: {
		ID:           Lmstudio,
		Slug:         "lmstudio",
		EnvVar:       "LM_STUDIO_API_KEY",
		DefaultModel: "",
		BaseURL:      "http://localhost:1234",
	},
	Minimax: {
		ID:           Minimax,
		Slug:         "minimax",
		EnvVar:       "MINIMAX_API_KEY",
		DefaultModel: "MiniMax-Text-01",
		BaseURL:      "https://api.minimax.chat",
	},
	Mistral: {
		ID:           Mistral,
		Slug:         "mistral",
		EnvVar:       "MISTRAL_API_KEY",
		DefaultModel: "mistral-large-latest",
		BaseURL:      "https://api.mistral.ai",
	},
	Moonshot: {
		ID:           Moonshot,
		Slug:         "moonshot",
		EnvVar:       "MOONSHOT_API_KEY",
		DefaultModel: "moonshot-v1-8k",
		BaseURL:      "https://api.moonshot.ai",
	},
	Ollama: {
		ID:           Ollama,
		Slug:         "ollama",
		EnvVar:       "OLLAMA_API_KEY",
		DefaultModel: "",
		BaseURL:      "http://localhost:11434",
	},
	OpenAI: {
		ID:           OpenAI,
		Slug:         "openai",
		EnvVar:       "OPENAI_API_KEY",
		DefaultModel: "gpt-4o-2024-08-06",
		BaseURL:      "https://api.openai.com",
	},
	Openrouter: {
		ID:           Openrouter,
		Slug:         "openrouter",
		EnvVar:       "OPENROUTER_API_KEY",
		DefaultModel: "openai/gpt-4o",
		BaseURL:      "https://openrouter.ai/api",
	},
	Perplexity: {
		ID:           Perplexity,
		Slug:         "perplexity",
		EnvVar:       "PERPLEXITY_API_KEY",
		DefaultModel: "sonar-pro",
		BaseURL:      "https://api.perplexity.ai",
	},
	Pixverse: {
		ID:           Pixverse,
		Slug:         "pixverse",
		EnvVar:       "PIXVERSE_API_KEY",
		DefaultModel: "v4.5",
		BaseURL:      "https://app-api.pixverse.ai",
	},
	Qwen: {
		ID:           Qwen,
		Slug:         "qwen",
		EnvVar:       "DASHSCOPE_API_KEY",
		DefaultModel: "qwen-plus",
		BaseURL:      "https://dashscope-intl.aliyuncs.com/compatible-mode",
	},
	Recraft: {
		ID:           Recraft,
		Slug:         "recraft",
		EnvVar:       "RECRAFT_API_TOKEN",
		DefaultModel: "recraftv3",
		BaseURL:      "https://external.api.recraft.ai",
	},
	Sambanova: {
		ID:           Sambanova,
		Slug:         "sambanova",
		EnvVar:       "SAMBANOVA_API_KEY",
		DefaultModel: "Meta-Llama-3.3-70B-Instruct",
		BaseURL:      "https://api.sambanova.ai",
	},
	Together: {
		ID:           Together,
		Slug:         "together",
		EnvVar:       "TOGETHER_API_KEY",
		DefaultModel: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
		BaseURL:      "https://api.together.xyz",
	},
	Vertex: {
		ID:           Vertex,
		Slug:         "vertex",
		EnvVar:       "VERTEX_BEARER_TOKEN",
		DefaultModel: "imagen-3.0-generate-002",
		BaseURL:      "https://{location}-aiplatform.googleapis.com/v1/projects/{project_id}/locations/{location}/publishers/google/models",
	},
	Vidu: {
		ID:           Vidu,
		Slug:         "vidu",
		EnvVar:       "VIDU_API_KEY",
		DefaultModel: "viduq3-pro",
		BaseURL:      "https://api.vidu.com",
	},
	Vllm: {
		ID:           Vllm,
		Slug:         "vllm",
		EnvVar:       "VLLM_API_KEY",
		DefaultModel: "",
		BaseURL:      "http://localhost:8000",
	},
	Workersai: {
		ID:           Workersai,
		Slug:         "workersai",
		EnvVar:       "CLOUDFLARE_API_TOKEN",
		DefaultModel: "@cf/meta/llama-3.1-8b-instruct",
		BaseURL:      "https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/v1",
	},
	Yi: {
		ID:           Yi,
		Slug:         "yi",
		EnvVar:       "YI_API_KEY",
		DefaultModel: "yi-large",
		BaseURL:      "https://api.01.ai",
	},
	Zhipu: {
		ID:           Zhipu,
		Slug:         "zhipu",
		EnvVar:       "ZHIPU_API_KEY",
		DefaultModel: "glm-4-plus",
		BaseURL:      "https://open.bigmodel.cn/api/paas",
	},
}
