// Code generated by codegen/generate.py; DO NOT EDIT.

package providers

// Provider name constants.
const (
	AI21       = "ai21"
	Anthropic  = "anthropic"
	Azure      = "azure"
	Bedrock    = "bedrock"
	Cerebras   = "cerebras"
	Cohere     = "cohere"
	Deepseek   = "deepseek"
	Doubao     = "doubao"
	Ernie      = "ernie"
	Fireworks  = "fireworks"
	Google     = "google"
	Grok       = "grok"
	Groq       = "groq"
	Jan        = "jan"
	Llamacpp   = "llamacpp"
	Lmstudio   = "lmstudio"
	Minimax    = "minimax"
	Mistral    = "mistral"
	Moonshot   = "moonshot"
	Ollama     = "ollama"
	OpenAI     = "openai"
	Openrouter = "openrouter"
	Perplexity = "perplexity"
	Qwen       = "qwen"
	Sambanova  = "sambanova"
	Together   = "together"
	Vertex     = "vertex"
	Vllm       = "vllm"
	Yi         = "yi"
	Zhipu      = "zhipu"
)
