// Code generated by codegen/generate.py; DO NOT EDIT.

package providers

// System message placement strategies.
const (
	PlacementTopLevelField  = "TopLevelField"
	PlacementMessageInArray = "MessageInArray"
	PlacementSiblingObject  = "SiblingObject"
)

// Authentication schemes.
const (
	AuthBearerToken   = "BearerToken"
	AuthHeaderAPIKey  = "HeaderAPIKey"
	AuthQueryParamKey = "QueryParamKey"
	AuthSigV4         = "SigV4"
)

// StructuredOutputDef holds provider-specific structured output configuration.
type StructuredOutputDef struct {
	FormatField           string
	FormatType            string
	SchemaPath            string
	BetaHeader            string
	EnforceStrict         bool
	RemoveAdditionalProps bool
}

// StructuredOutput returns the structured output config for a provider.
func StructuredOutput(provider string) *StructuredOutputDef {
	switch provider {
	case Anthropic:
		return &StructuredOutputDef{
			FormatField:           "output_format",
			FormatType:            "json_schema",
			SchemaPath:            "schema",
			BetaHeader:            "structured-outputs-2025-11-13",
			EnforceStrict:         true,
			RemoveAdditionalProps: false,
		}
	case Azure:
		return &StructuredOutputDef{
			FormatField:           "response_format",
			FormatType:            "json_schema",
			SchemaPath:            "json_schema.schema",
			BetaHeader:            "",
			EnforceStrict:         true,
			RemoveAdditionalProps: false,
		}
	case Google:
		return &StructuredOutputDef{
			FormatField:           "generationConfig.responseMimeType",
			FormatType:            "application/json",
			SchemaPath:            "generationConfig.responseSchema",
			BetaHeader:            "",
			EnforceStrict:         false,
			RemoveAdditionalProps: true,
		}
	case Grok:
		return &StructuredOutputDef{
			FormatField:           "response_format",
			FormatType:            "json_schema",
			SchemaPath:            "json_schema.schema",
			BetaHeader:            "",
			EnforceStrict:         true,
			RemoveAdditionalProps: false,
		}
	case Mistral:
		return &StructuredOutputDef{
			FormatField:           "response_format",
			FormatType:            "json_schema",
			SchemaPath:            "json_schema.schema",
			BetaHeader:            "",
			EnforceStrict:         true,
			RemoveAdditionalProps: false,
		}
	case OpenAI:
		return &StructuredOutputDef{
			FormatField:           "response_format",
			FormatType:            "json_schema",
			SchemaPath:            "json_schema.schema",
			BetaHeader:            "",
			EnforceStrict:         true,
			RemoveAdditionalProps: false,
		}
	default:
		return nil
	}
}

// ToolCallDef holds provider-specific tool call configuration.
type ToolCallDef struct {
	ArgsFormat string // "map" or "json_string"
	ResultRole string
	IDSource   string // "id_field" or "function_name"
}

// ToolCallConfig returns the tool call config for a provider.
func ToolCallConfig(provider string) *ToolCallDef {
	switch provider {
	case Ai21:
		return &ToolCallDef{
			ArgsFormat: "json_string",
			ResultRole: "tool",
			IDSource:   "id_field",
		}
	case Anthropic:
		return &ToolCallDef{
			ArgsFormat: "map",
			ResultRole: "user",
			IDSource:   "id_field",
		}
	case Azure:
		return &ToolCallDef{
			ArgsFormat: "json_string",
			ResultRole: "tool",
			IDSource:   "id_field",
		}
	case Bedrock:
		return &ToolCallDef{
			ArgsFormat: "map",
			ResultRole: "user",
			IDSource:   "id_field",
		}
	case Cerebras:
		return &ToolCallDef{
			ArgsFormat: "json_string",
			ResultRole: "tool",
			IDSource:   "id_field",
		}
	case Cohere:
		return &ToolCallDef{
			ArgsFormat: "json_string",
			ResultRole: "tool",
			IDSource:   "id_field",
		}
	case Deepseek:
		return &ToolCallDef{
			ArgsFormat: "json_string",
			ResultRole: "tool",
			IDSource:   "id_field",
		}
	case Doubao:
		return &ToolCallDef{
			ArgsFormat: "json_string",
			ResultRole: "tool",
			IDSource:   "id_field",
		}
	case Ernie:
		return &ToolCallDef{
			ArgsFormat: "json_string",
			ResultRole: "tool",
			IDSource:   "id_field",
		}
	case Fireworks:
		return &ToolCallDef{
			ArgsFormat: "json_string",
			ResultRole: "tool",
			IDSource:   "id_field",
		}
	case Google:
		return &ToolCallDef{
			ArgsFormat: "map",
			ResultRole: "user",
			IDSource:   "function_name",
		}
	case Grok:
		return &ToolCallDef{
			ArgsFormat: "json_string",
			ResultRole: "tool",
			IDSource:   "id_field",
		}
	case Groq:
		return &ToolCallDef{
			ArgsFormat: "json_string",
			ResultRole: "tool",
			IDSource:   "id_field",
		}
	case Lmstudio:
		return &ToolCallDef{
			ArgsFormat: "json_string",
			ResultRole: "tool",
			IDSource:   "id_field",
		}
	case Minimax:
		return &ToolCallDef{
			ArgsFormat: "json_string",
			ResultRole: "tool",
			IDSource:   "id_field",
		}
	case Mistral:
		return &ToolCallDef{
			ArgsFormat: "json_string",
			ResultRole: "tool",
			IDSource:   "id_field",
		}
	case Moonshot:
		return &ToolCallDef{
			ArgsFormat: "json_string",
			ResultRole: "tool",
			IDSource:   "id_field",
		}
	case Ollama:
		return &ToolCallDef{
			ArgsFormat: "json_string",
			ResultRole: "tool",
			IDSource:   "id_field",
		}
	case OpenAI:
		return &ToolCallDef{
			ArgsFormat: "json_string",
			ResultRole: "tool",
			IDSource:   "id_field",
		}
	case Openrouter:
		return &ToolCallDef{
			ArgsFormat: "json_string",
			ResultRole: "tool",
			IDSource:   "id_field",
		}
	case Qwen:
		return &ToolCallDef{
			ArgsFormat: "json_string",
			ResultRole: "tool",
			IDSource:   "id_field",
		}
	case Sambanova:
		return &ToolCallDef{
			ArgsFormat: "json_string",
			ResultRole: "tool",
			IDSource:   "id_field",
		}
	case Together:
		return &ToolCallDef{
			ArgsFormat: "json_string",
			ResultRole: "tool",
			IDSource:   "id_field",
		}
	case Vllm:
		return &ToolCallDef{
			ArgsFormat: "json_string",
			ResultRole: "tool",
			IDSource:   "id_field",
		}
	case Zhipu:
		return &ToolCallDef{
			ArgsFormat: "json_string",
			ResultRole: "tool",
			IDSource:   "id_field",
		}
	default:
		return nil
	}
}

// FileUploadDef holds provider-specific file upload configuration.
type FileUploadDef struct {
	Endpoint         string
	FieldName        string
	ExtraFields      string // JSON object of extra form fields
	BetaHeader       string
	ResponseIdPath   string
	ResponseUriPath  string
	ResponseNamePath string
	ResponseMimePath string
	RefType          string // content block type for file references
	RefIdField       string // dotted path to file ID in reference block
	RefUriField      string // dotted path to file URI in reference block
	RefMimeField     string // dotted path to MIME type in reference block
	RefExtraFields   string // JSON of static sibling fields for file reference
}

// FileUploadConfig returns the file upload config for a provider.
func FileUploadConfig(provider string) *FileUploadDef {
	switch provider {
	case Anthropic:
		return &FileUploadDef{
			Endpoint:         "/v1/files",
			FieldName:        "file",
			ExtraFields:      ``,
			BetaHeader:       "files-api-2025-04-14",
			ResponseIdPath:   "id",
			ResponseUriPath:  "",
			ResponseNamePath: "filename",
			ResponseMimePath: "mime_type",
			RefType:          "document",
			RefIdField:       "source.file_id",
			RefUriField:      "",
			RefMimeField:     "",
			RefExtraFields:   `{"source":{"type":"file"}}`,
		}
	case Google:
		return &FileUploadDef{
			Endpoint:         "/upload/v1beta/files",
			FieldName:        "file",
			ExtraFields:      ``,
			BetaHeader:       "",
			ResponseIdPath:   "file.name",
			ResponseUriPath:  "file.uri",
			ResponseNamePath: "file.displayName",
			ResponseMimePath: "file.mimeType",
			RefType:          "fileData",
			RefIdField:       "",
			RefUriField:      "fileData.fileUri",
			RefMimeField:     "fileData.mimeType",
			RefExtraFields:   ``,
		}
	case Grok:
		return &FileUploadDef{
			Endpoint:         "/v1/files",
			FieldName:        "file",
			ExtraFields:      `{"purpose":"assistants"}`,
			BetaHeader:       "",
			ResponseIdPath:   "id",
			ResponseUriPath:  "",
			ResponseNamePath: "filename",
			ResponseMimePath: "",
			RefType:          "",
			RefIdField:       "",
			RefUriField:      "",
			RefMimeField:     "",
			RefExtraFields:   ``,
		}
	case OpenAI:
		return &FileUploadDef{
			Endpoint:         "/v1/files",
			FieldName:        "file",
			ExtraFields:      `{"purpose":"assistants"}`,
			BetaHeader:       "",
			ResponseIdPath:   "id",
			ResponseUriPath:  "",
			ResponseNamePath: "filename",
			ResponseMimePath: "",
			RefType:          "file",
			RefIdField:       "file.file_id",
			RefUriField:      "",
			RefMimeField:     "",
			RefExtraFields:   ``,
		}
	default:
		return nil
	}
}
