// Code generated by codegen/generate.py; DO NOT EDIT.

package providers

// System message placement strategies.
const (
	PlacementTopLevelField  = "TopLevelField"
	PlacementMessageInArray = "MessageInArray"
	PlacementSiblingObject  = "SiblingObject"
)

// Chat wire shapes — the request/response transform family selected
// per chat protocol (ADR-055). The runtime switches on ChatWireShape
// instead of inferring the family from SystemPlacement/auth (ADR-047).
const (
	ChatOpenAI          = "ChatOpenAI"
	ChatAnthropic       = "ChatAnthropic"
	ChatGoogle          = "ChatGoogle"
	ChatBedrock         = "ChatBedrock"
	ChatResponsesOpenAI = "ChatResponsesOpenAI"
)

// Authentication schemes.
const (
	AuthBearerToken   = "BearerToken"
	AuthHeaderAPIKey  = "HeaderAPIKey"
	AuthQueryParamKey = "QueryParamKey"
	AuthSigV4         = "SigV4"
)

// StructuredOutputDef holds provider-specific structured output configuration.
type StructuredOutputDef struct {
	FormatField           string
	FormatType            string
	SchemaPath            string
	BetaHeader            string
	EnforceStrict         bool
	RemoveAdditionalProps bool
	SchemaPlacement       string // "WrappedInFormat" (default) or "SiblingOfFormat"
}

// StructuredOutput returns the structured output config for a provider.
func StructuredOutput(provider string) *StructuredOutputDef {
	switch ProviderName(provider) {
	case Anthropic:
		return &StructuredOutputDef{
			FormatField:           "output_format",
			FormatType:            "json_schema",
			SchemaPath:            "schema",
			BetaHeader:            "structured-outputs-2025-11-13",
			EnforceStrict:         true,
			RemoveAdditionalProps: false,
			SchemaPlacement:       "WrappedInFormat",
		}
	case Azure:
		return &StructuredOutputDef{
			FormatField:           "response_format",
			FormatType:            "json_schema",
			SchemaPath:            "json_schema.schema",
			BetaHeader:            "",
			EnforceStrict:         true,
			RemoveAdditionalProps: false,
			SchemaPlacement:       "WrappedInFormat",
		}
	case Google:
		return &StructuredOutputDef{
			FormatField:           "generationConfig.responseMimeType",
			FormatType:            "application/json",
			SchemaPath:            "generationConfig.responseSchema",
			BetaHeader:            "",
			EnforceStrict:         false,
			RemoveAdditionalProps: true,
			SchemaPlacement:       "SiblingOfFormat",
		}
	case Grok:
		return &StructuredOutputDef{
			FormatField:           "response_format",
			FormatType:            "json_schema",
			SchemaPath:            "json_schema.schema",
			BetaHeader:            "",
			EnforceStrict:         true,
			RemoveAdditionalProps: false,
			SchemaPlacement:       "WrappedInFormat",
		}
	case Mistral:
		return &StructuredOutputDef{
			FormatField:           "response_format",
			FormatType:            "json_schema",
			SchemaPath:            "json_schema.schema",
			BetaHeader:            "",
			EnforceStrict:         true,
			RemoveAdditionalProps: false,
			SchemaPlacement:       "WrappedInFormat",
		}
	case OpenAI:
		return &StructuredOutputDef{
			FormatField:           "response_format",
			FormatType:            "json_schema",
			SchemaPath:            "json_schema.schema",
			BetaHeader:            "",
			EnforceStrict:         true,
			RemoveAdditionalProps: false,
			SchemaPlacement:       "WrappedInFormat",
		}
	default:
		return nil
	}
}

// ToolCallDef holds provider-specific tool call configuration.
type ToolCallDef struct {
	ArgsFormat      string // "map" or "json_string"
	ResultRole      string
	IDSource        string // "id_field" or "function_name"
	ParamsWireField string // JSON key for tool params (ADR-025); "parameters" default
}

// ToolCallConfig returns the tool call config for a provider.
func ToolCallConfig(provider string) *ToolCallDef {
	switch ProviderName(provider) {
	case AI21:
		return &ToolCallDef{
			ArgsFormat:      "json_string",
			ResultRole:      "tool",
			IDSource:        "id_field",
			ParamsWireField: "parameters",
		}
	case Anthropic:
		return &ToolCallDef{
			ArgsFormat:      "map",
			ResultRole:      "user",
			IDSource:        "id_field",
			ParamsWireField: "parameters",
		}
	case Azure:
		return &ToolCallDef{
			ArgsFormat:      "json_string",
			ResultRole:      "tool",
			IDSource:        "id_field",
			ParamsWireField: "parameters",
		}
	case Bedrock:
		return &ToolCallDef{
			ArgsFormat:      "map",
			ResultRole:      "user",
			IDSource:        "id_field",
			ParamsWireField: "parameters",
		}
	case Cerebras:
		return &ToolCallDef{
			ArgsFormat:      "json_string",
			ResultRole:      "tool",
			IDSource:        "id_field",
			ParamsWireField: "parameters",
		}
	case Cohere:
		return &ToolCallDef{
			ArgsFormat:      "json_string",
			ResultRole:      "tool",
			IDSource:        "id_field",
			ParamsWireField: "parameters",
		}
	case Deepseek:
		return &ToolCallDef{
			ArgsFormat:      "json_string",
			ResultRole:      "tool",
			IDSource:        "id_field",
			ParamsWireField: "parameters",
		}
	case Doubao:
		return &ToolCallDef{
			ArgsFormat:      "json_string",
			ResultRole:      "tool",
			IDSource:        "id_field",
			ParamsWireField: "parameters",
		}
	case Ernie:
		return &ToolCallDef{
			ArgsFormat:      "json_string",
			ResultRole:      "tool",
			IDSource:        "id_field",
			ParamsWireField: "parameters",
		}
	case Fireworks:
		return &ToolCallDef{
			ArgsFormat:      "json_string",
			ResultRole:      "tool",
			IDSource:        "id_field",
			ParamsWireField: "parameters",
		}
	case Google:
		return &ToolCallDef{
			ArgsFormat:      "map",
			ResultRole:      "user",
			IDSource:        "function_name",
			ParamsWireField: "parametersJsonSchema",
		}
	case Grok:
		return &ToolCallDef{
			ArgsFormat:      "json_string",
			ResultRole:      "tool",
			IDSource:        "id_field",
			ParamsWireField: "parameters",
		}
	case Groq:
		return &ToolCallDef{
			ArgsFormat:      "json_string",
			ResultRole:      "tool",
			IDSource:        "id_field",
			ParamsWireField: "parameters",
		}
	case Jan:
		return &ToolCallDef{
			ArgsFormat:      "json_string",
			ResultRole:      "tool",
			IDSource:        "id_field",
			ParamsWireField: "parameters",
		}
	case Llamacpp:
		return &ToolCallDef{
			ArgsFormat:      "json_string",
			ResultRole:      "tool",
			IDSource:        "id_field",
			ParamsWireField: "parameters",
		}
	case Lmstudio:
		return &ToolCallDef{
			ArgsFormat:      "json_string",
			ResultRole:      "tool",
			IDSource:        "id_field",
			ParamsWireField: "parameters",
		}
	case Minimax:
		return &ToolCallDef{
			ArgsFormat:      "json_string",
			ResultRole:      "tool",
			IDSource:        "id_field",
			ParamsWireField: "parameters",
		}
	case Mistral:
		return &ToolCallDef{
			ArgsFormat:      "json_string",
			ResultRole:      "tool",
			IDSource:        "id_field",
			ParamsWireField: "parameters",
		}
	case Moonshot:
		return &ToolCallDef{
			ArgsFormat:      "json_string",
			ResultRole:      "tool",
			IDSource:        "id_field",
			ParamsWireField: "parameters",
		}
	case Ollama:
		return &ToolCallDef{
			ArgsFormat:      "json_string",
			ResultRole:      "tool",
			IDSource:        "id_field",
			ParamsWireField: "parameters",
		}
	case OpenAI:
		return &ToolCallDef{
			ArgsFormat:      "json_string",
			ResultRole:      "tool",
			IDSource:        "id_field",
			ParamsWireField: "parameters",
		}
	case Openrouter:
		return &ToolCallDef{
			ArgsFormat:      "json_string",
			ResultRole:      "tool",
			IDSource:        "id_field",
			ParamsWireField: "parameters",
		}
	case Qwen:
		return &ToolCallDef{
			ArgsFormat:      "json_string",
			ResultRole:      "tool",
			IDSource:        "id_field",
			ParamsWireField: "parameters",
		}
	case Sambanova:
		return &ToolCallDef{
			ArgsFormat:      "json_string",
			ResultRole:      "tool",
			IDSource:        "id_field",
			ParamsWireField: "parameters",
		}
	case Together:
		return &ToolCallDef{
			ArgsFormat:      "json_string",
			ResultRole:      "tool",
			IDSource:        "id_field",
			ParamsWireField: "parameters",
		}
	case Vllm:
		return &ToolCallDef{
			ArgsFormat:      "json_string",
			ResultRole:      "tool",
			IDSource:        "id_field",
			ParamsWireField: "parameters",
		}
	case Zhipu:
		return &ToolCallDef{
			ArgsFormat:      "json_string",
			ResultRole:      "tool",
			IDSource:        "id_field",
			ParamsWireField: "parameters",
		}
	default:
		return nil
	}
}

// FileUploadDef holds provider-specific file upload configuration.
type FileUploadDef struct {
	Endpoint         string
	FieldName        string
	ExtraFields      string // JSON object of extra form fields
	BetaHeader       string
	ResponseIdPath   string
	ResponseUriPath  string
	ResponseNamePath string
	ResponseMimePath string
	RefType          string // content block type for file references
	RefIdField       string // dotted path to file ID in reference block
	RefUriField      string // dotted path to file URI in reference block
	RefMimeField     string // dotted path to MIME type in reference block
	RefExtraFields   string // JSON of static sibling fields for file reference
}

// FileUploadConfig returns the file upload config for a provider.
func FileUploadConfig(provider string) *FileUploadDef {
	switch ProviderName(provider) {
	case Anthropic:
		return &FileUploadDef{
			Endpoint:         "/v1/files",
			FieldName:        "file",
			ExtraFields:      ``,
			BetaHeader:       "files-api-2025-04-14",
			ResponseIdPath:   "id",
			ResponseUriPath:  "",
			ResponseNamePath: "filename",
			ResponseMimePath: "mime_type",
			RefType:          "document",
			RefIdField:       "source.file_id",
			RefUriField:      "",
			RefMimeField:     "",
			RefExtraFields:   `{"source":{"type":"file"}}`,
		}
	case Google:
		return &FileUploadDef{
			Endpoint:         "/upload/v1beta/files",
			FieldName:        "file",
			ExtraFields:      ``,
			BetaHeader:       "",
			ResponseIdPath:   "file.name",
			ResponseUriPath:  "file.uri",
			ResponseNamePath: "file.displayName",
			ResponseMimePath: "file.mimeType",
			RefType:          "fileData",
			RefIdField:       "",
			RefUriField:      "fileData.fileUri",
			RefMimeField:     "fileData.mimeType",
			RefExtraFields:   ``,
		}
	case Grok:
		return &FileUploadDef{
			Endpoint:         "/v1/files",
			FieldName:        "file",
			ExtraFields:      `{"purpose":"assistants"}`,
			BetaHeader:       "",
			ResponseIdPath:   "id",
			ResponseUriPath:  "",
			ResponseNamePath: "filename",
			ResponseMimePath: "",
			RefType:          "",
			RefIdField:       "",
			RefUriField:      "",
			RefMimeField:     "",
			RefExtraFields:   ``,
		}
	case OpenAI:
		return &FileUploadDef{
			Endpoint:         "/v1/files",
			FieldName:        "file",
			ExtraFields:      `{"purpose":"assistants"}`,
			BetaHeader:       "",
			ResponseIdPath:   "id",
			ResponseUriPath:  "",
			ResponseNamePath: "filename",
			ResponseMimePath: "",
			RefType:          "file",
			RefIdField:       "file.file_id",
			RefUriField:      "",
			RefMimeField:     "",
			RefExtraFields:   ``,
		}
	default:
		return nil
	}
}
