// Code generated by codegen/generate.py; DO NOT EDIT.

package providers

// ResponseTextPath returns the JSON path to extract text from a provider response.
func ResponseTextPath(provider string) string {
	switch provider {
	case Ai21:
		return "choices[0].message.content"
	case Anthropic:
		return "content[0].text"
	case Azure:
		return "choices[0].message.content"
	case Bedrock:
		return "output.message.content[0].text"
	case Cerebras:
		return "choices[0].message.content"
	case Cohere:
		return "choices[0].message.content"
	case Deepseek:
		return "choices[0].message.content"
	case Doubao:
		return "choices[0].message.content"
	case Ernie:
		return "choices[0].message.content"
	case Fireworks:
		return "choices[0].message.content"
	case Google:
		return "candidates[0].content.parts[0].text"
	case Grok:
		return "choices[0].message.content"
	case Groq:
		return "choices[0].message.content"
	case Lmstudio:
		return "choices[0].message.content"
	case Minimax:
		return "choices[0].message.content"
	case Mistral:
		return "choices[0].message.content"
	case Moonshot:
		return "choices[0].message.content"
	case Ollama:
		return "choices[0].message.content"
	case OpenAI:
		return "choices[0].message.content"
	case Openrouter:
		return "choices[0].message.content"
	case Perplexity:
		return "choices[0].message.content"
	case Qwen:
		return "choices[0].message.content"
	case Sambanova:
		return "choices[0].message.content"
	case Together:
		return "choices[0].message.content"
	case Vllm:
		return "choices[0].message.content"
	case Yi:
		return "choices[0].message.content"
	case Zhipu:
		return "choices[0].message.content"
	default:
		return ""
	}
}

// UsagePaths returns the JSON paths for input and output token counts.
func UsagePaths(provider string) (inputPath, outputPath string) {
	switch provider {
	case Ai21:
		return "usage.prompt_tokens", "usage.completion_tokens"
	case Anthropic:
		return "usage.input_tokens", "usage.output_tokens"
	case Azure:
		return "usage.prompt_tokens", "usage.completion_tokens"
	case Bedrock:
		return "usage.inputTokens", "usage.outputTokens"
	case Cerebras:
		return "usage.prompt_tokens", "usage.completion_tokens"
	case Cohere:
		return "usage.prompt_tokens", "usage.completion_tokens"
	case Deepseek:
		return "usage.prompt_tokens", "usage.completion_tokens"
	case Doubao:
		return "usage.prompt_tokens", "usage.completion_tokens"
	case Ernie:
		return "usage.prompt_tokens", "usage.completion_tokens"
	case Fireworks:
		return "usage.prompt_tokens", "usage.completion_tokens"
	case Google:
		return "usageMetadata.promptTokenCount", "usageMetadata.candidatesTokenCount"
	case Grok:
		return "usage.prompt_tokens", "usage.completion_tokens"
	case Groq:
		return "usage.prompt_tokens", "usage.completion_tokens"
	case Lmstudio:
		return "usage.prompt_tokens", "usage.completion_tokens"
	case Minimax:
		return "usage.prompt_tokens", "usage.completion_tokens"
	case Mistral:
		return "usage.prompt_tokens", "usage.completion_tokens"
	case Moonshot:
		return "usage.prompt_tokens", "usage.completion_tokens"
	case Ollama:
		return "usage.prompt_tokens", "usage.completion_tokens"
	case OpenAI:
		return "usage.prompt_tokens", "usage.completion_tokens"
	case Openrouter:
		return "usage.prompt_tokens", "usage.completion_tokens"
	case Perplexity:
		return "usage.prompt_tokens", "usage.completion_tokens"
	case Qwen:
		return "usage.prompt_tokens", "usage.completion_tokens"
	case Sambanova:
		return "usage.prompt_tokens", "usage.completion_tokens"
	case Together:
		return "usage.prompt_tokens", "usage.completion_tokens"
	case Vllm:
		return "usage.prompt_tokens", "usage.completion_tokens"
	case Yi:
		return "usage.prompt_tokens", "usage.completion_tokens"
	case Zhipu:
		return "usage.prompt_tokens", "usage.completion_tokens"
	default:
		return "", ""
	}
}
