// Code generated by codegen/generate.py; DO NOT EDIT.

package providers

// StreamDef holds provider-specific streaming configuration.
type StreamDef struct {
	Endpoint        string // alternate endpoint for streaming (empty = same as non-streaming)
	Param           string // request body field to enable streaming
	ParamValue      string // value for the stream param
	DeltaTextPath   string // JSON path to text delta in SSE event data
	DoneSignal      string // string that signals end of stream
	UsesEventTypes  bool   // whether provider uses named SSE event types
	ContentEvent    string // SSE event type for content deltas
	DoneEvent       string // SSE event type for stream end
	UsageEvent      string // SSE event type for usage data
	UsageInputPath  string
	UsageOutputPath string
}

// StreamConfig returns the streaming config for a provider.
func StreamConfig(provider string) *StreamDef {
	switch provider {
	case Ai21:
		return &StreamDef{
			Endpoint:        "",
			Param:           "stream",
			ParamValue:      "true",
			DeltaTextPath:   "choices[0].delta.content",
			DoneSignal:      "[DONE]",
			UsesEventTypes:  false,
			ContentEvent:    "",
			DoneEvent:       "",
			UsageEvent:      "",
			UsageInputPath:  "usage.prompt_tokens",
			UsageOutputPath: "usage.completion_tokens",
		}
	case Anthropic:
		return &StreamDef{
			Endpoint:        "",
			Param:           "stream",
			ParamValue:      "true",
			DeltaTextPath:   "delta.text",
			DoneSignal:      "message_stop",
			UsesEventTypes:  true,
			ContentEvent:    "content_block_delta",
			DoneEvent:       "message_stop",
			UsageEvent:      "message_delta",
			UsageInputPath:  "usage.input_tokens",
			UsageOutputPath: "usage.output_tokens",
		}
	case Azure:
		return &StreamDef{
			Endpoint:        "",
			Param:           "stream",
			ParamValue:      "true",
			DeltaTextPath:   "choices[0].delta.content",
			DoneSignal:      "[DONE]",
			UsesEventTypes:  false,
			ContentEvent:    "",
			DoneEvent:       "",
			UsageEvent:      "",
			UsageInputPath:  "usage.prompt_tokens",
			UsageOutputPath: "usage.completion_tokens",
		}
	case Cerebras:
		return &StreamDef{
			Endpoint:        "",
			Param:           "stream",
			ParamValue:      "true",
			DeltaTextPath:   "choices[0].delta.content",
			DoneSignal:      "[DONE]",
			UsesEventTypes:  false,
			ContentEvent:    "",
			DoneEvent:       "",
			UsageEvent:      "",
			UsageInputPath:  "usage.prompt_tokens",
			UsageOutputPath: "usage.completion_tokens",
		}
	case Cohere:
		return &StreamDef{
			Endpoint:        "",
			Param:           "stream",
			ParamValue:      "true",
			DeltaTextPath:   "choices[0].delta.content",
			DoneSignal:      "[DONE]",
			UsesEventTypes:  false,
			ContentEvent:    "",
			DoneEvent:       "",
			UsageEvent:      "",
			UsageInputPath:  "usage.prompt_tokens",
			UsageOutputPath: "usage.completion_tokens",
		}
	case Deepseek:
		return &StreamDef{
			Endpoint:        "",
			Param:           "stream",
			ParamValue:      "true",
			DeltaTextPath:   "choices[0].delta.content",
			DoneSignal:      "[DONE]",
			UsesEventTypes:  false,
			ContentEvent:    "",
			DoneEvent:       "",
			UsageEvent:      "",
			UsageInputPath:  "usage.prompt_tokens",
			UsageOutputPath: "usage.completion_tokens",
		}
	case Doubao:
		return &StreamDef{
			Endpoint:        "",
			Param:           "stream",
			ParamValue:      "true",
			DeltaTextPath:   "choices[0].delta.content",
			DoneSignal:      "[DONE]",
			UsesEventTypes:  false,
			ContentEvent:    "",
			DoneEvent:       "",
			UsageEvent:      "",
			UsageInputPath:  "usage.prompt_tokens",
			UsageOutputPath: "usage.completion_tokens",
		}
	case Ernie:
		return &StreamDef{
			Endpoint:        "",
			Param:           "stream",
			ParamValue:      "true",
			DeltaTextPath:   "choices[0].delta.content",
			DoneSignal:      "[DONE]",
			UsesEventTypes:  false,
			ContentEvent:    "",
			DoneEvent:       "",
			UsageEvent:      "",
			UsageInputPath:  "usage.prompt_tokens",
			UsageOutputPath: "usage.completion_tokens",
		}
	case Fireworks:
		return &StreamDef{
			Endpoint:        "",
			Param:           "stream",
			ParamValue:      "true",
			DeltaTextPath:   "choices[0].delta.content",
			DoneSignal:      "[DONE]",
			UsesEventTypes:  false,
			ContentEvent:    "",
			DoneEvent:       "",
			UsageEvent:      "",
			UsageInputPath:  "usage.prompt_tokens",
			UsageOutputPath: "usage.completion_tokens",
		}
	case Google:
		return &StreamDef{
			Endpoint:        "/v1beta/models/{model}:streamGenerateContent?alt=sse",
			Param:           "",
			ParamValue:      "",
			DeltaTextPath:   "candidates[0].content.parts[0].text",
			DoneSignal:      "",
			UsesEventTypes:  false,
			ContentEvent:    "",
			DoneEvent:       "",
			UsageEvent:      "",
			UsageInputPath:  "usageMetadata.promptTokenCount",
			UsageOutputPath: "usageMetadata.candidatesTokenCount",
		}
	case Grok:
		return &StreamDef{
			Endpoint:        "",
			Param:           "stream",
			ParamValue:      "true",
			DeltaTextPath:   "choices[0].delta.content",
			DoneSignal:      "[DONE]",
			UsesEventTypes:  false,
			ContentEvent:    "",
			DoneEvent:       "",
			UsageEvent:      "",
			UsageInputPath:  "usage.prompt_tokens",
			UsageOutputPath: "usage.completion_tokens",
		}
	case Groq:
		return &StreamDef{
			Endpoint:        "",
			Param:           "stream",
			ParamValue:      "true",
			DeltaTextPath:   "choices[0].delta.content",
			DoneSignal:      "[DONE]",
			UsesEventTypes:  false,
			ContentEvent:    "",
			DoneEvent:       "",
			UsageEvent:      "",
			UsageInputPath:  "usage.prompt_tokens",
			UsageOutputPath: "usage.completion_tokens",
		}
	case Lmstudio:
		return &StreamDef{
			Endpoint:        "",
			Param:           "stream",
			ParamValue:      "true",
			DeltaTextPath:   "choices[0].delta.content",
			DoneSignal:      "[DONE]",
			UsesEventTypes:  false,
			ContentEvent:    "",
			DoneEvent:       "",
			UsageEvent:      "",
			UsageInputPath:  "usage.prompt_tokens",
			UsageOutputPath: "usage.completion_tokens",
		}
	case Minimax:
		return &StreamDef{
			Endpoint:        "",
			Param:           "stream",
			ParamValue:      "true",
			DeltaTextPath:   "choices[0].delta.content",
			DoneSignal:      "[DONE]",
			UsesEventTypes:  false,
			ContentEvent:    "",
			DoneEvent:       "",
			UsageEvent:      "",
			UsageInputPath:  "usage.prompt_tokens",
			UsageOutputPath: "usage.completion_tokens",
		}
	case Mistral:
		return &StreamDef{
			Endpoint:        "",
			Param:           "stream",
			ParamValue:      "true",
			DeltaTextPath:   "choices[0].delta.content",
			DoneSignal:      "[DONE]",
			UsesEventTypes:  false,
			ContentEvent:    "",
			DoneEvent:       "",
			UsageEvent:      "",
			UsageInputPath:  "usage.prompt_tokens",
			UsageOutputPath: "usage.completion_tokens",
		}
	case Moonshot:
		return &StreamDef{
			Endpoint:        "",
			Param:           "stream",
			ParamValue:      "true",
			DeltaTextPath:   "choices[0].delta.content",
			DoneSignal:      "[DONE]",
			UsesEventTypes:  false,
			ContentEvent:    "",
			DoneEvent:       "",
			UsageEvent:      "",
			UsageInputPath:  "usage.prompt_tokens",
			UsageOutputPath: "usage.completion_tokens",
		}
	case Ollama:
		return &StreamDef{
			Endpoint:        "",
			Param:           "stream",
			ParamValue:      "true",
			DeltaTextPath:   "choices[0].delta.content",
			DoneSignal:      "[DONE]",
			UsesEventTypes:  false,
			ContentEvent:    "",
			DoneEvent:       "",
			UsageEvent:      "",
			UsageInputPath:  "usage.prompt_tokens",
			UsageOutputPath: "usage.completion_tokens",
		}
	case OpenAI:
		return &StreamDef{
			Endpoint:        "",
			Param:           "stream",
			ParamValue:      "true",
			DeltaTextPath:   "choices[0].delta.content",
			DoneSignal:      "[DONE]",
			UsesEventTypes:  false,
			ContentEvent:    "",
			DoneEvent:       "",
			UsageEvent:      "",
			UsageInputPath:  "usage.prompt_tokens",
			UsageOutputPath: "usage.completion_tokens",
		}
	case Openrouter:
		return &StreamDef{
			Endpoint:        "",
			Param:           "stream",
			ParamValue:      "true",
			DeltaTextPath:   "choices[0].delta.content",
			DoneSignal:      "[DONE]",
			UsesEventTypes:  false,
			ContentEvent:    "",
			DoneEvent:       "",
			UsageEvent:      "",
			UsageInputPath:  "usage.prompt_tokens",
			UsageOutputPath: "usage.completion_tokens",
		}
	case Perplexity:
		return &StreamDef{
			Endpoint:        "",
			Param:           "stream",
			ParamValue:      "true",
			DeltaTextPath:   "choices[0].delta.content",
			DoneSignal:      "[DONE]",
			UsesEventTypes:  false,
			ContentEvent:    "",
			DoneEvent:       "",
			UsageEvent:      "",
			UsageInputPath:  "usage.prompt_tokens",
			UsageOutputPath: "usage.completion_tokens",
		}
	case Qwen:
		return &StreamDef{
			Endpoint:        "",
			Param:           "stream",
			ParamValue:      "true",
			DeltaTextPath:   "choices[0].delta.content",
			DoneSignal:      "[DONE]",
			UsesEventTypes:  false,
			ContentEvent:    "",
			DoneEvent:       "",
			UsageEvent:      "",
			UsageInputPath:  "usage.prompt_tokens",
			UsageOutputPath: "usage.completion_tokens",
		}
	case Sambanova:
		return &StreamDef{
			Endpoint:        "",
			Param:           "stream",
			ParamValue:      "true",
			DeltaTextPath:   "choices[0].delta.content",
			DoneSignal:      "[DONE]",
			UsesEventTypes:  false,
			ContentEvent:    "",
			DoneEvent:       "",
			UsageEvent:      "",
			UsageInputPath:  "usage.prompt_tokens",
			UsageOutputPath: "usage.completion_tokens",
		}
	case Together:
		return &StreamDef{
			Endpoint:        "",
			Param:           "stream",
			ParamValue:      "true",
			DeltaTextPath:   "choices[0].delta.content",
			DoneSignal:      "[DONE]",
			UsesEventTypes:  false,
			ContentEvent:    "",
			DoneEvent:       "",
			UsageEvent:      "",
			UsageInputPath:  "usage.prompt_tokens",
			UsageOutputPath: "usage.completion_tokens",
		}
	case Vllm:
		return &StreamDef{
			Endpoint:        "",
			Param:           "stream",
			ParamValue:      "true",
			DeltaTextPath:   "choices[0].delta.content",
			DoneSignal:      "[DONE]",
			UsesEventTypes:  false,
			ContentEvent:    "",
			DoneEvent:       "",
			UsageEvent:      "",
			UsageInputPath:  "usage.prompt_tokens",
			UsageOutputPath: "usage.completion_tokens",
		}
	case Yi:
		return &StreamDef{
			Endpoint:        "",
			Param:           "stream",
			ParamValue:      "true",
			DeltaTextPath:   "choices[0].delta.content",
			DoneSignal:      "[DONE]",
			UsesEventTypes:  false,
			ContentEvent:    "",
			DoneEvent:       "",
			UsageEvent:      "",
			UsageInputPath:  "usage.prompt_tokens",
			UsageOutputPath: "usage.completion_tokens",
		}
	case Zhipu:
		return &StreamDef{
			Endpoint:        "",
			Param:           "stream",
			ParamValue:      "true",
			DeltaTextPath:   "choices[0].delta.content",
			DoneSignal:      "[DONE]",
			UsesEventTypes:  false,
			ContentEvent:    "",
			DoneEvent:       "",
			UsageEvent:      "",
			UsageInputPath:  "usage.prompt_tokens",
			UsageOutputPath: "usage.completion_tokens",
		}
	default:
		return nil
	}
}
