// Code generated by codegen/generate.py; DO NOT EDIT.

package providers

// Telemetry OTEL GenAI binding facts + attribute mappings (ADR-054),
// generated from the ontology. The handwritten fail-open OTLP exporter
// reads these; a semantic-convention move is a mapping edit in the
// ontology + regenerate, never a hand-edit here or in the exporter.

// TelemetrySemconvVersion is the pinned OTEL GenAI semconv version the exporter emits.
const TelemetrySemconvVersion = "1.29.0"

// TelemetryTracesPath is appended to the caller endpoint for the OTLP/HTTP traces POST.
const TelemetryTracesPath = "/v1/traces"

// TelemetryEndpointRequired reports whether a non-empty endpoint is mandatory at construction.
const TelemetryEndpointRequired = true

// TelemetryCaptureContentDefault is the default for the tier-2 content-capture gate.
const TelemetryCaptureContentDefault = false

// OTEL GenAI attribute keys (api:mapsToOtelAttribute).
const (
	OtelAttrOp       = "gen_ai.operation.name" // Event.Op
	OtelAttrProvider = "gen_ai.system"         // Event.Provider
	OtelAttrModel    = "gen_ai.request.model"  // Event.Model
	OtelAttrErr      = "error.type"            // Event.Err
)

// OTEL GenAI usage attribute keys (llm:otelUsageAttribute).
const (
	OtelUsageInput  = "gen_ai.usage.input_tokens"  // Usage.Input
	OtelUsageOutput = "gen_ai.usage.output_tokens" // Usage.Output
)

// TelemetryOperationName maps a MiddlewareOp to its gen_ai.operation.name value.
// Operations without a documented semconv value are absent (honest).
var TelemetryOperationName = map[MiddlewareOp]string{
	OpLLMRequest: "chat",
	OpToolCall:   "execute_tool",
}
