// Code generated by codegen/generate.py; DO NOT EDIT.

package providers

// Video wire-shape discriminators. Each selects the submit-body build,
// poll mechanism, and result-extraction transform.
const (
	VideoShapeGrok  = "VideoGrok"
	VideoShapeZhipu = "VideoZhipu"
)

// Video output-delivery modes. Drive whether the runtime downloads
// bytes, returns a provider URL, or requires a caller S3 URI.
const (
	VideoDeliveryDownload  = "DeliveryDownload"
	VideoDeliveryURL       = "DeliveryURL"
	VideoDeliveryOutputURI = "DeliveryOutputURI"
)

// VideoModelDef describes one video-generation model. MaxDurationSeconds
// is 0 when the provider documents no fixed ceiling.
type VideoModelDef struct {
	ModelID              string
	Label                string
	SupportsImageToVideo bool
	MaxDurationSeconds   int
	OutputMime           string
	Resolutions          []string
}

// VideoGenDef holds one provider's video-generation configuration.
// GenEndpoint is the submit endpoint path. RequiresOutputURI is true
// only for caller-S3 providers (Bedrock Nova Reel).
type VideoGenDef struct {
	WireShape         string // VideoShapeGrok | VideoShapeZhipu
	OutputDelivery    string // VideoDeliveryDownload | VideoDeliveryURL | VideoDeliveryOutputURI
	GenEndpoint       string // submit endpoint path
	RequiresOutputURI bool
	Models            []VideoModelDef
}

// VideoGenConfig returns the video-generation config for a provider, or nil
// if the provider does not support video generation.
func VideoGenConfig(provider string) *VideoGenDef {
	switch provider {
	case Grok:
		return &VideoGenDef{
			WireShape:         "VideoGrok",
			OutputDelivery:    "DeliveryURL",
			GenEndpoint:       "/v1/videos/generations",
			RequiresOutputURI: false,
			Models: []VideoModelDef{
				{
					ModelID:              "grok-imagine-video",
					Label:                "Grok Imagine Video",
					SupportsImageToVideo: true,
					MaxDurationSeconds:   15,
					OutputMime:           "video/mp4",
					Resolutions:          []string{"480p", "720p"},
				},
			},
		}
	case Zhipu:
		return &VideoGenDef{
			WireShape:         "VideoZhipu",
			OutputDelivery:    "DeliveryURL",
			GenEndpoint:       "/v4/videos/generations",
			RequiresOutputURI: false,
			Models: []VideoModelDef{
				{
					ModelID:              "cogvideox-3",
					Label:                "CogVideoX-3",
					SupportsImageToVideo: true,
					MaxDurationSeconds:   10,
					OutputMime:           "video/mp4",
					Resolutions:          []string{"1080p", "4k", "720p"},
				},
			},
		}
	default:
		return nil
	}
}
