// Code generated by codegen/generate.py; DO NOT EDIT.

// Package builders is the typed-builder API surface introduced in
// ADR-009 / plan 016. Phase 2b emitted skeleton types + panicking
// terminals; phase 3 wires the chain state into struct fields and
// hand-writes a subset of terminals against the legacy free-function
// runtime (see text.go, image.go in this package). Phase 4 will move
// this surface into the main llmkit package once the legacy
// free-function API is deleted.
package builders

import (
	"context"

	llmkit "github.com/aktagon/llmkit-go"
)

// === Type aliases — phase 4 deletes when this package merges into main ===

type Message = llmkit.Message
type Tool = llmkit.Tool
type MiddlewareFn = llmkit.MiddlewareFn
type Response = llmkit.Response
type ImageResponse = llmkit.ImageResponse
type ImageData = llmkit.ImageData
type File = llmkit.File
type Part = llmkit.Part
type Provider = llmkit.Provider

// BatchHandle is a value struct identifying a submitted batch.
// Faithful migration of the legacy llmkit.BatchHandle shape; the
// Wait method (in batch.go) calls llmkit.WaitBatch internally.
// Cross-process resume works by persisting {ID, Provider} and
// reconstructing the struct.
type BatchHandle struct {
	ID       string
	Provider Provider
}

// providerConfig holds per-provider auth + endpoint details. Phase 4
// promotes it to a public type aligned with llmkit.Provider.
// baseURL is an internal override mainly used by tests pointing at
// httptest.Server URLs; per-provider constructors leave it empty so
// the legacy provider config supplies the canonical endpoint.
type providerConfig struct {
	name    string
	apiKey  string
	baseURL string
}

// toLlmkit converts the internal config to the legacy llmkit.Provider
// shape consumed by the existing free-function runtime.
func (pc providerConfig) toLlmkit(model string) llmkit.Provider {
	return llmkit.Provider{Name: pc.name, APIKey: pc.apiKey, Model: model, BaseURL: pc.baseURL}
}

// Client is the entry point for the typed-builder API. Each
// sub-namespace field is a *<Capability> builder prototype tied to
// this client; chain methods return new instances, the field stays
// constant.
type Client struct {
	provider providerConfig
	Text     *Text
	Image    *Image
	Agent    *Agent
	Upload   *Upload
}

func newClient(name, apiKey string) *Client {
	c := &Client{provider: providerConfig{name: name, apiKey: apiKey}}
	c.Text = &Text{client: c}
	c.Image = &Image{client: c}
	c.Agent = &Agent{client: c}
	c.Upload = &Upload{client: c}
	return c
}

// New constructs a Client for the named provider. Per-provider
// helpers below are ergonomic shortcuts.
func New(name, apiKey string) *Client { return newClient(name, apiKey) }

// === Per-provider constructors ===
func Ai21(apiKey string) *Client       { return newClient("ai21", apiKey) }
func Anthropic(apiKey string) *Client  { return newClient("anthropic", apiKey) }
func Azure(apiKey string) *Client      { return newClient("azure", apiKey) }
func Bedrock(apiKey string) *Client    { return newClient("bedrock", apiKey) }
func Cerebras(apiKey string) *Client   { return newClient("cerebras", apiKey) }
func Cohere(apiKey string) *Client     { return newClient("cohere", apiKey) }
func Deepseek(apiKey string) *Client   { return newClient("deepseek", apiKey) }
func Doubao(apiKey string) *Client     { return newClient("doubao", apiKey) }
func Ernie(apiKey string) *Client      { return newClient("ernie", apiKey) }
func Fireworks(apiKey string) *Client  { return newClient("fireworks", apiKey) }
func Google(apiKey string) *Client     { return newClient("google", apiKey) }
func Grok(apiKey string) *Client       { return newClient("grok", apiKey) }
func Groq(apiKey string) *Client       { return newClient("groq", apiKey) }
func Lmstudio(apiKey string) *Client   { return newClient("lmstudio", apiKey) }
func Minimax(apiKey string) *Client    { return newClient("minimax", apiKey) }
func Mistral(apiKey string) *Client    { return newClient("mistral", apiKey) }
func Moonshot(apiKey string) *Client   { return newClient("moonshot", apiKey) }
func Ollama(apiKey string) *Client     { return newClient("ollama", apiKey) }
func Openai(apiKey string) *Client     { return newClient("openai", apiKey) }
func Openrouter(apiKey string) *Client { return newClient("openrouter", apiKey) }
func Perplexity(apiKey string) *Client { return newClient("perplexity", apiKey) }
func Qwen(apiKey string) *Client       { return newClient("qwen", apiKey) }
func Sambanova(apiKey string) *Client  { return newClient("sambanova", apiKey) }
func Together(apiKey string) *Client   { return newClient("together", apiKey) }
func Vllm(apiKey string) *Client       { return newClient("vllm", apiKey) }
func Yi(apiKey string) *Client         { return newClient("yi", apiKey) }
func Zhipu(apiKey string) *Client      { return newClient("zhipu", apiKey) }

// === *Text — ChatCompletion builder ===

// Text accumulates configuration for a ChatCompletion
// call. Chain methods return new instances (immutable); skipped
// terminals live in hand-written text.go / image.go.
type Text struct {
	client      *Client
	caching     bool
	files       []llmkit.File
	history     []llmkit.Message
	parts       []llmkit.Part
	maxTokens   *int
	middleware  []llmkit.MiddlewareFn
	model       string
	schema      string
	system      string
	temperature *float64
}

func (b *Text) Caching() *Text { out := *b; out.caching = true; return &out }
func (b *Text) File(id string) *Text {
	out := *b
	out.files = append(out.files, llmkit.File{ID: id})
	return &out
}                                                    // ordered
func (b *Text) History(msgs ...llmkit.Message) *Text { out := *b; out.history = msgs; return &out }
func (b *Text) Image(mime string, data []byte) *Text {
	out := *b
	out.parts = append(out.parts, llmkit.Image(mime, data))
	return &out
}                                     // ordered
func (b *Text) MaxTokens(n int) *Text { out := *b; v := n; out.maxTokens = &v; return &out }
func (b *Text) Middleware(fns ...llmkit.MiddlewareFn) *Text {
	out := *b
	out.middleware = append(out.middleware, fns...)
	return &out
}
func (b *Text) Model(name string) *Text     { out := *b; out.model = name; return &out }
func (b *Text) Schema(s string) *Text       { out := *b; out.schema = s; return &out }
func (b *Text) System(s string) *Text       { out := *b; out.system = s; return &out }
func (b *Text) Temperature(t float64) *Text { out := *b; v := t; out.temperature = &v; return &out }
func (b *Text) Text(s string) *Text {
	out := *b
	out.parts = append(out.parts, llmkit.Text(s))
	return &out
} // ordered

// === *Image — ImageGeneration builder ===

// Image accumulates configuration for a ImageGeneration
// call. Chain methods return new instances (immutable); skipped
// terminals live in hand-written text.go / image.go.
type Image struct {
	client      *Client
	aspectRatio string
	caching     bool
	parts       []llmkit.Part
	imageSize   string
	includeText bool
	middleware  []llmkit.MiddlewareFn
	model       string
}

func (b *Image) AspectRatio(r string) *Image { out := *b; out.aspectRatio = r; return &out }
func (b *Image) Caching() *Image             { out := *b; out.caching = true; return &out }
func (b *Image) Image(mime string, data []byte) *Image {
	out := *b
	out.parts = append(out.parts, llmkit.Image(mime, data))
	return &out
}                                          // ordered
func (b *Image) ImageSize(s string) *Image { out := *b; out.imageSize = s; return &out }
func (b *Image) IncludeText() *Image       { out := *b; out.includeText = true; return &out }
func (b *Image) Middleware(fns ...llmkit.MiddlewareFn) *Image {
	out := *b
	out.middleware = append(out.middleware, fns...)
	return &out
}
func (b *Image) Model(name string) *Image { out := *b; out.model = name; return &out }
func (b *Image) Text(s string) *Image {
	out := *b
	out.parts = append(out.parts, llmkit.Text(s))
	return &out
} // ordered

// === *Agent — ToolCalling builder ===

// Agent accumulates configuration for a ToolCalling
// call. Chain methods return new instances (immutable); skipped
// terminals live in hand-written text.go / image.go.
type Agent struct {
	client      *Client
	caching     bool
	maxTokens   *int
	middleware  []llmkit.MiddlewareFn
	model       string
	system      string
	temperature *float64
	tools       []llmkit.Tool
}

func (b *Agent) Caching() *Agent        { out := *b; out.caching = true; return &out }
func (b *Agent) MaxTokens(n int) *Agent { out := *b; v := n; out.maxTokens = &v; return &out }
func (b *Agent) Middleware(fns ...llmkit.MiddlewareFn) *Agent {
	out := *b
	out.middleware = append(out.middleware, fns...)
	return &out
}
func (b *Agent) Model(name string) *Agent     { out := *b; out.model = name; return &out }
func (b *Agent) System(s string) *Agent       { out := *b; out.system = s; return &out }
func (b *Agent) Temperature(t float64) *Agent { out := *b; v := t; out.temperature = &v; return &out }
func (b *Agent) Tool(t llmkit.Tool) *Agent    { out := *b; out.tools = append(out.tools, t); return &out }

func (b *Agent) Prompt(ctx context.Context, msg string) (Response, error) {
	panic("plan 016 phase 3: *Agent.Prompt not yet implemented")
}
func (b *Agent) Reset() {
	panic("plan 016 phase 3: *Agent.Reset not yet implemented")
}

// === *Upload — FileUpload builder ===

// Upload accumulates configuration for a FileUpload
// call. Chain methods return new instances (immutable); skipped
// terminals live in hand-written text.go / image.go.
type Upload struct {
	client     *Client
	bytes      []byte
	filename   string
	middleware []llmkit.MiddlewareFn
	mimeType   string
	path       string
}

func (b *Upload) Bytes(data []byte) *Upload    { out := *b; out.bytes = data; return &out }
func (b *Upload) Filename(name string) *Upload { out := *b; out.filename = name; return &out }
func (b *Upload) Middleware(fns ...llmkit.MiddlewareFn) *Upload {
	out := *b
	out.middleware = append(out.middleware, fns...)
	return &out
}
func (b *Upload) MimeType(mime string) *Upload { out := *b; out.mimeType = mime; return &out }
func (b *Upload) Path(p string) *Upload        { out := *b; out.path = p; return &out }
