// Code generated by codegen/generate.py; DO NOT EDIT.

// Package builders is the typed-builder API surface introduced in
// ADR-009 / plan 016. Skeleton emission (phase 2b): types compile and
// chain methods return new copies, but terminals (Prompt, Stream,
// Generate, Run, Wait) are stubs that panic until phase 3 wires up the
// runtime. Phase 4 will move this surface into the main llmkit package
// once the legacy free-function API is removed.
package builders

import (
	"context"
	"iter"
)

// === Stub types — phase 4 replaces with imports from main llmkit package ===

type Message struct{ Role string }
type Tool interface{}
type MiddlewareFn func() error
type Response struct{ Text string }
type ImageResponse struct{}
type BatchHandle struct {
	ID       string
	Provider string
}
type File struct{ ID string }

// providerConfig holds per-provider auth + endpoint details. Phase 3
// expands the shape; phase 4 promotes it to a public type aligned
// with the main llmkit Provider.
type providerConfig struct {
	name   string
	apiKey string
}

// Client is the entry point for the typed-builder API. Each
// sub-namespace field is a *<Capability> builder prototype tied to
// this client; chain methods return new instances, the field stays
// constant.
type Client struct {
	provider providerConfig
	Text     *Text
	Image    *Image
	Agent    *Agent
	Upload   *Upload
}

func newClient(name, apiKey string) *Client {
	c := &Client{provider: providerConfig{name: name, apiKey: apiKey}}
	c.Text = &Text{client: c}
	c.Image = &Image{client: c}
	c.Agent = &Agent{client: c}
	c.Upload = &Upload{client: c}
	return c
}

// New constructs a Client for the named provider. Per-provider
// helpers below are ergonomic shortcuts.
func New(name, apiKey string) *Client { return newClient(name, apiKey) }

// === Per-provider constructors ===
func Ai21(apiKey string) *Client       { return newClient("ai21", apiKey) }
func Anthropic(apiKey string) *Client  { return newClient("anthropic", apiKey) }
func Azure(apiKey string) *Client      { return newClient("azure", apiKey) }
func Bedrock(apiKey string) *Client    { return newClient("bedrock", apiKey) }
func Cerebras(apiKey string) *Client   { return newClient("cerebras", apiKey) }
func Cohere(apiKey string) *Client     { return newClient("cohere", apiKey) }
func Deepseek(apiKey string) *Client   { return newClient("deepseek", apiKey) }
func Doubao(apiKey string) *Client     { return newClient("doubao", apiKey) }
func Ernie(apiKey string) *Client      { return newClient("ernie", apiKey) }
func Fireworks(apiKey string) *Client  { return newClient("fireworks", apiKey) }
func Google(apiKey string) *Client     { return newClient("google", apiKey) }
func Grok(apiKey string) *Client       { return newClient("grok", apiKey) }
func Groq(apiKey string) *Client       { return newClient("groq", apiKey) }
func Lmstudio(apiKey string) *Client   { return newClient("lmstudio", apiKey) }
func Minimax(apiKey string) *Client    { return newClient("minimax", apiKey) }
func Mistral(apiKey string) *Client    { return newClient("mistral", apiKey) }
func Moonshot(apiKey string) *Client   { return newClient("moonshot", apiKey) }
func Ollama(apiKey string) *Client     { return newClient("ollama", apiKey) }
func Openai(apiKey string) *Client     { return newClient("openai", apiKey) }
func Openrouter(apiKey string) *Client { return newClient("openrouter", apiKey) }
func Perplexity(apiKey string) *Client { return newClient("perplexity", apiKey) }
func Qwen(apiKey string) *Client       { return newClient("qwen", apiKey) }
func Sambanova(apiKey string) *Client  { return newClient("sambanova", apiKey) }
func Together(apiKey string) *Client   { return newClient("together", apiKey) }
func Vllm(apiKey string) *Client       { return newClient("vllm", apiKey) }
func Yi(apiKey string) *Client         { return newClient("yi", apiKey) }
func Zhipu(apiKey string) *Client      { return newClient("zhipu", apiKey) }

// === *Text — ChatCompletion builder ===

// Text accumulates configuration for a ChatCompletion
// call. Chain methods return new instances (immutable); terminals
// are panic stubs until plan-016 phase 3 lands runtime wiring.
type Text struct {
	client *Client
	// Phase 3: chained-config fields (system, parts, history, etc.)
}

func (b *Text) Caching() *Text                       { out := *b; return &out }
func (b *Text) File(id string) *Text                 { out := *b; return &out } // ordered: parts accumulator
func (b *Text) History(msgs ...Message) *Text        { out := *b; return &out }
func (b *Text) Image(mime string, data []byte) *Text { out := *b; return &out } // ordered: parts accumulator
func (b *Text) MaxTokens(n int) *Text                { out := *b; return &out }
func (b *Text) Middleware(fns ...MiddlewareFn) *Text { out := *b; return &out }
func (b *Text) Model(name string) *Text              { out := *b; return &out }
func (b *Text) Schema(s string) *Text                { out := *b; return &out }
func (b *Text) System(s string) *Text                { out := *b; return &out }
func (b *Text) Temperature(t float64) *Text          { out := *b; return &out }
func (b *Text) Text(s string) *Text                  { out := *b; return &out } // ordered: parts accumulator

func (b *Text) Prompt(ctx context.Context, finalText string) (Response, error) {
	panic("plan 016 phase 3: *Text.Prompt not yet implemented")
}
func (b *Text) Stream(ctx context.Context, finalText string) iter.Seq2[string, error] {
	panic("plan 016 phase 3: *Text.Stream not yet implemented")
}
func (b *Text) Batch(ctx context.Context, prompts ...string) ([]Response, error) {
	panic("plan 016 phase 3: *Text.Batch not yet implemented")
}
func (b *Text) SubmitBatch(ctx context.Context, prompts ...string) (BatchHandle, error) {
	panic("plan 016 phase 3: *Text.SubmitBatch not yet implemented")
}

// === *Image — ImageGeneration builder ===

// Image accumulates configuration for a ImageGeneration
// call. Chain methods return new instances (immutable); terminals
// are panic stubs until plan-016 phase 3 lands runtime wiring.
type Image struct {
	client *Client
	// Phase 3: chained-config fields (system, parts, history, etc.)
}

func (b *Image) AspectRatio(r string) *Image           { out := *b; return &out }
func (b *Image) Caching() *Image                       { out := *b; return &out }
func (b *Image) Image(mime string, data []byte) *Image { out := *b; return &out } // ordered: parts accumulator
func (b *Image) ImageSize(s string) *Image             { out := *b; return &out }
func (b *Image) IncludeText() *Image                   { out := *b; return &out }
func (b *Image) Middleware(fns ...MiddlewareFn) *Image { out := *b; return &out }
func (b *Image) Model(name string) *Image              { out := *b; return &out }
func (b *Image) Text(s string) *Image                  { out := *b; return &out } // ordered: parts accumulator

func (b *Image) Generate(ctx context.Context, finalText string) (ImageResponse, error) {
	panic("plan 016 phase 3: *Image.Generate not yet implemented")
}

// === *Agent — ToolCalling builder ===

// Agent accumulates configuration for a ToolCalling
// call. Chain methods return new instances (immutable); terminals
// are panic stubs until plan-016 phase 3 lands runtime wiring.
type Agent struct {
	client *Client
	// Phase 3: chained-config fields (system, parts, history, etc.)
}

func (b *Agent) Caching() *Agent                       { out := *b; return &out }
func (b *Agent) MaxTokens(n int) *Agent                { out := *b; return &out }
func (b *Agent) Middleware(fns ...MiddlewareFn) *Agent { out := *b; return &out }
func (b *Agent) Model(name string) *Agent              { out := *b; return &out }
func (b *Agent) System(s string) *Agent                { out := *b; return &out }
func (b *Agent) Temperature(t float64) *Agent          { out := *b; return &out }
func (b *Agent) Tool(t Tool) *Agent                    { out := *b; return &out }

func (b *Agent) Prompt(ctx context.Context, msg string) (Response, error) {
	panic("plan 016 phase 3: *Agent.Prompt not yet implemented")
}
func (b *Agent) Reset() {
	panic("plan 016 phase 3: *Agent.Reset not yet implemented")
}

// === *Upload — FileUpload builder ===

// Upload accumulates configuration for a FileUpload
// call. Chain methods return new instances (immutable); terminals
// are panic stubs until plan-016 phase 3 lands runtime wiring.
type Upload struct {
	client *Client
	// Phase 3: chained-config fields (system, parts, history, etc.)
}

func (b *Upload) Bytes(data []byte) *Upload              { out := *b; return &out }
func (b *Upload) Filename(name string) *Upload           { out := *b; return &out }
func (b *Upload) Middleware(fns ...MiddlewareFn) *Upload { out := *b; return &out }
func (b *Upload) MimeType(mime string) *Upload           { out := *b; return &out }
func (b *Upload) Path(p string) *Upload                  { out := *b; return &out }

func (b *Upload) Run(ctx context.Context) (File, error) {
	panic("plan 016 phase 3: *Upload.Run not yet implemented")
}

// === BatchHandle terminal ===

func (h *BatchHandle) Wait(ctx context.Context) ([]Response, error) {
	panic("plan 016 phase 3: BatchHandle.Wait not yet implemented")
}
